export const CLOSE_IMPORT_KRONOS_LABOR_DRIVERS_VALIDATION_ERRORS = 'CLOSE_IMPORT_KRONOS_LABOR_DRIVERS_VALIDATION_ERRORS';

export function closeImportLaborDriversValidationErrors() {
  return {
    type: CLOSE_IMPORT_KRONOS_LABOR_DRIVERS_VALIDATION_ERRORS,
  };
}
