export const SHOW_IMPORT_KRONOS_LABOR_DRIVERS_VALIDATION_ERRORS = 'SHOW_IMPORT_KRONOS_LABOR_DRIVERS_VALIDATION_ERRORS';

export function showImportLaborDriversValidationErrors() {
  return {
    type: SHOW_IMPORT_KRONOS_LABOR_DRIVERS_VALIDATION_ERRORS,
  };
}
