export const STANDARDS_LIST_OPTION_DEPARTMENTS = 'DEPARTMENTS';
export const STANDARDS_LIST_OPTION_CLASSIFICATIONS = 'CLASSIFICATIONS';
export const STANDARDS_LIST_OPTION_JOB_CLASSES = 'JOB_CLASSES';
export const STANDARDS_LIST_OPTION_LABOR_CATEGORIES = 'LABOR_CATEGORIES';
export const STANDARDS_LIST_OPTION_UNITS_OF_MEASURE = 'UNITS_OF_MEASURE';
export const STANDARDS_LIST_OPTION_VOLUME_DRIVERS = 'VOLUME_DRIVERS';
export const STANDARDS_LIST_OPTION_FILING_FIELD = 'FILING_FIELD';
