import {http} from '../../shared/services';

export const GET_STANDARD_FILING_FIELDS_AS_SELECT_LISTS_OPTIONS = 'GET_STANDARD_FILING_FIELDS_AS_SELECT_LISTS_OPTIONS';
export const GET_STANDARD_FILING_FIELDS_AS_SELECT_LISTS_OPTIONS_PENDING = `${GET_STANDARD_FILING_FIELDS_AS_SELECT_LISTS_OPTIONS}_PENDING`;
export const GET_STANDARD_FILING_FIELDS_AS_SELECT_LISTS_OPTIONS_REJECTED = `${GET_STANDARD_FILING_FIELDS_AS_SELECT_LISTS_OPTIONS}_REJECTED`;
export const GET_STANDARD_FILING_FIELDS_AS_SELECT_LISTS_OPTIONS_FULFILLED = `${GET_STANDARD_FILING_FIELDS_AS_SELECT_LISTS_OPTIONS}_FULFILLED`;

export function getFilingFieldsAsSelectListOptions() {
  return {
    type: GET_STANDARD_FILING_FIELDS_AS_SELECT_LISTS_OPTIONS,
    payload: http.get('standard-filing-fields/as-options-list'),
  };
}
