export const ADD_AFTER_CLOSE_HOURS_LIST_ITEM_FOR_EDIT = 'ADD_KRONOS_LABOR_PERIOD_AFTER_CLOSE_HOURS_LIST_ITEM_FOR_EDIT';

export function addAfterCloseHoursListItemForEdit() {
  return {
    type: ADD_AFTER_CLOSE_HOURS_LIST_ITEM_FOR_EDIT,
  };
}
