export const ADD_ABSOLUTE_HOURS_LIST_ITEM_FOR_CREATE = 'ADD_KRONOS_LABOR_PERIOD_ABSOLUTE_HOURS_LIST_ITEM_FOR_CREATE';

export function addAbsoluteHoursListItemForCreate() {
  return {
    type: ADD_ABSOLUTE_HOURS_LIST_ITEM_FOR_CREATE,
  };
}
