export const ADD_AFTER_CLOSE_HOURS_LIST_ITEM_FOR_CREATE = 'ADD_KRONOS_LABOR_PERIOD_AFTER_CLOSE_HOURS_LIST_ITEM_FOR_CREATE';

export function addAfterCloseHoursListItemForCreate() {
  return {
    type: ADD_AFTER_CLOSE_HOURS_LIST_ITEM_FOR_CREATE,
  };
}
