export const ADD_AFTER_OPEN_HOURS_LIST_ITEM_FOR_CREATE = 'ADD_KRONOS_LABOR_PERIOD_AFTER_OPEN_HOURS_LIST_ITEM_FOR_CREATE';

export function addAfterOpenHoursListItemForCreate() {
  return {
    type: ADD_AFTER_OPEN_HOURS_LIST_ITEM_FOR_CREATE,
  };
}
