export const ADD_OPERATION_HOURS_LIST_ITEM_FOR_CREATE = 'ADD_KRONOS_LABOR_PERIOD_OPERATION_HOURS_LIST_ITEM_FOR_CREATE';

export function addOperationHoursListItemForCreate() {
  return {
    type: ADD_OPERATION_HOURS_LIST_ITEM_FOR_CREATE,
  };
}
