export const CLOSE_IMPORT_LABOR_PERIODS_VALIDATION_ERRORS = 'CLOSE_IMPORT_LABOR_PERIODS_VALIDATION_ERRORS';

export function closeImportLaborPeriodsValidationErrors() {
  return {
    type: CLOSE_IMPORT_LABOR_PERIODS_VALIDATION_ERRORS,
  };
}
