export const CLEAR_LABOR_STANDARDS_LIST_FILTERS = 'CLEAR_LABOR_STANDARDS_LIST_FILTERS';
export const CLEAR_LABOR_STANDARDS_LIST_FILTERS_PENDING = `${CLEAR_LABOR_STANDARDS_LIST_FILTERS}_PENDING`;
export const CLEAR_LABOR_STANDARDS_LIST_FILTERS_FULFILLED = `${CLEAR_LABOR_STANDARDS_LIST_FILTERS}_FULFILLED`;
export const CLEAR_LABOR_STANDARDS_LIST_FILTERS_REJECTED = `${CLEAR_LABOR_STANDARDS_LIST_FILTERS}_REJECTED`;

export function clearLaborStandardsListFilters() {
  return {
    type: CLEAR_LABOR_STANDARDS_LIST_FILTERS,
    payload: Promise.resolve(),
  };
}
