export const CLEAR_LABOR_STANDARDS_LIST_SORTS = 'CLEAR_LABOR_STANDARDS_LIST_SORTS';
export const CLEAR_LABOR_STANDARDS_LIST_SORTS_PENDING = `${CLEAR_LABOR_STANDARDS_LIST_SORTS}_PENDING`;
export const CLEAR_LABOR_STANDARDS_LIST_SORTS_FULFILLED = `${CLEAR_LABOR_STANDARDS_LIST_SORTS}_FULFILLED`;
export const CLEAR_LABOR_STANDARDS_LIST_SORTS_REJECTED = `${CLEAR_LABOR_STANDARDS_LIST_SORTS}_REJECTED`;

export function clearLaborStandardsListSorts() {
  return {
    type: CLEAR_LABOR_STANDARDS_LIST_SORTS,
    payload: Promise.resolve(),
  };
}
