export const CLOSE_IMPORT_KRONOS_LABOR_STANDARDS_VALIDATION_ERRORS = 'CLOSE_IMPORT_KRONOS_LABOR_STANDARDS_VALIDATION_ERRORS';

export function closeImportLaborStandardsValidationErrors() {
  return {
    type: CLOSE_IMPORT_KRONOS_LABOR_STANDARDS_VALIDATION_ERRORS,
  };
}
