export const FILTER_LABOR_STANDARDS_LIST = 'FILTER_LABOR_STANDARDS_LIST';
export const FILTER_LABOR_STANDARDS_LIST_PENDING = `${FILTER_LABOR_STANDARDS_LIST}_PENDING`;
export const FILTER_LABOR_STANDARDS_LIST_FULFILLED = `${FILTER_LABOR_STANDARDS_LIST}_FULFILLED`;
export const FILTER_LABOR_STANDARDS_LIST_REJECTED = `${FILTER_LABOR_STANDARDS_LIST}_REJECTED`;

export function filterLaborStandardsList(filter) {
  return {
    type: FILTER_LABOR_STANDARDS_LIST,
    payload: Promise.resolve(filter),
  };
}
