export const SHOW_IMPORT_KRONOS_LABOR_STANDARDS_VALIDATION_ERRORS = 'SHOW_IMPORT_KRONOS_LABOR_STANDARDS_VALIDATION_ERRORS';

export function showImportLaborStandardsValidationErrors() {
  return {
    type: SHOW_IMPORT_KRONOS_LABOR_STANDARDS_VALIDATION_ERRORS,
  };
}
