export const CLOSE_EDIT_STANDARD_FILING_FIELD_OPTION_SIDEBAR = 'CLOSE_EDIT_STANDARD_FILING_FIELD_OPTION_SIDEBAR';

export function closeEditStandardFilingFieldOptionSidebar() {
  return {
    type: CLOSE_EDIT_STANDARD_FILING_FIELD_OPTION_SIDEBAR,
  };
}
