export const STANDARDS = 'STANDARDS';
export const ATTRIBUTES = 'ATTRIBUTES';
export const LOCATIONS_STANDARDS_EXPORT = 'LOCATIONS_STANDARDS_EXPORT';
export const LOCATIONS = 'LOCATIONS';
export const VOLUME_DRIVER_MAPPINGS = 'VOLUME_DRIVER_MAPPINGS';
export const LOCATION_MAPPING = 'LOCATION_MAPPING';
export const ELEMENTS = 'ELEMENTS';
export const VOLUME_DRIVER_VALUES = 'VOLUME_DRIVER_VALUES';
export const LABOR_STANDARDS = 'LABOR_STANDARDS';
export const CHARACTERISTICS = 'CHARACTERISTICS';

export const GRIDS = [
  STANDARDS,
  ATTRIBUTES,
  LOCATIONS_STANDARDS_EXPORT,
  LOCATIONS,
  VOLUME_DRIVER_MAPPINGS,
  LOCATION_MAPPING,
  ELEMENTS,
  VOLUME_DRIVER_VALUES,
  LABOR_STANDARDS,
  CHARACTERISTICS,
];
