export const CLOSE_ELEMENT_UNITS_OF_MEASURE_LIST_EDIT_SIDEBAR = 'CLOSE_ELEMENT_UNITS_OF_MEASURE_LIST_EDIT_SIDEBAR';

export function closeUnitsOfMeasureListEditSidebar() {
  return {
    type: CLOSE_ELEMENT_UNITS_OF_MEASURE_LIST_EDIT_SIDEBAR,
  };
}
