export const CLOSE_IMPORT_LOCATION_PROFILES_VALIDATION_ERRORS = 'CLOSE_IMPORT_LOCATION_PROFILES_VALIDATION_ERRORS';

export function closeImportLocationProfilesValidationErrors() {
  return {
    type: CLOSE_IMPORT_LOCATION_PROFILES_VALIDATION_ERRORS,
  };
}
