export const SHOW_IMPORT_LOCATION_PROFILES_VALIDATION_ERRORS = 'SHOW_IMPORT_LOCATION_PROFILES_VALIDATION_ERRORS';

export function showImportLocationProfilesValidationErrors() {
  return {
    type: SHOW_IMPORT_LOCATION_PROFILES_VALIDATION_ERRORS,
  };
}
