import {http} from '../../shared/services';

export const UPDATE_LOCATIONS_DEPARTMENT = 'UPDATE_LOCATIONS_DEPARTMENT';
export const UPDATE_LOCATIONS_DEPARTMENT_PENDING = `${UPDATE_LOCATIONS_DEPARTMENT}_PENDING`;
export const UPDATE_LOCATIONS_DEPARTMENT_FULFILLED = `${UPDATE_LOCATIONS_DEPARTMENT}_FULFILLED`;
export const UPDATE_LOCATIONS_DEPARTMENT_REJECTED = `${UPDATE_LOCATIONS_DEPARTMENT}_REJECTED`;

export const UPDATE_LOCATIONS_DEPARTMENT_BULK = 'UPDATE_LOCATIONS_DEPARTMENT_BULK';
export const UPDATE_LOCATIONS_DEPARTMENT_BULK_PENDING = `${UPDATE_LOCATIONS_DEPARTMENT_BULK}_PENDING`;
export const UPDATE_LOCATIONS_DEPARTMENT_BULK_FULFILLED = `${UPDATE_LOCATIONS_DEPARTMENT_BULK}_FULFILLED`;
export const UPDATE_LOCATIONS_DEPARTMENT_BULK_REJECTED = `${UPDATE_LOCATIONS_DEPARTMENT_BULK}_REJECTED`;

export function updateLocationsDepartment(locations, departmentId, updateAll, removeFlag, filters = null) {
  return {
    type: locations.length >= 20 ? UPDATE_LOCATIONS_DEPARTMENT_BULK : UPDATE_LOCATIONS_DEPARTMENT,
    payload: http.put('locations/update-department', {locations, departmentId, updateAll, removeFlag, filters}),
  };
}
