export const EDIT_STANDARD_ELEMENT_FREQUENCY = 'EDIT_STANDARD_ELEMENT_FREQUENCY';
export const EDIT_STANDARD_BULK_EDIT_FREQUENCY = 'EDIT_STANDARD_BULK_EDIT_FREQUENCY';
export const NEW_STANDARD_ELEMENT_FREQUENCY = 'NEW_STANDARD_ELEMENT_FREQUENCY';
