import {http} from '../../shared/services';

export const INDUSTRY_ELEMENTS_LOAD_MOST_ELEMENT_DETAILS = 'INDUSTRY_ELEMENTS/LOAD_MOST_ELEMENT_DETAILS';
export const INDUSTRY_ELEMENTS_LOAD_MOST_ELEMENT_DETAILS_REJECTED = `${INDUSTRY_ELEMENTS_LOAD_MOST_ELEMENT_DETAILS}_REJECTED`;
export const INDUSTRY_ELEMENTS_LOAD_MOST_ELEMENT_DETAILS_PENDING = `${INDUSTRY_ELEMENTS_LOAD_MOST_ELEMENT_DETAILS}_PENDING`;
export const INDUSTRY_ELEMENTS_LOAD_MOST_ELEMENT_DETAILS_FULFILLED = `${INDUSTRY_ELEMENTS_LOAD_MOST_ELEMENT_DETAILS}_FULFILLED`;

export function loadMOSTElementDetails(sourceId, id) {
  return {
    type: INDUSTRY_ELEMENTS_LOAD_MOST_ELEMENT_DETAILS,
    payload: http.get(`industry-elements/${sourceId}/most/details/${id}`),
  };
}
