export const ABSOLUTE_HOURS = 'Absolute Hours';
export const OPERATION_HOURS = 'Hours of Operation';
export const AFTER_OPEN_HOURS = 'After Open Hours';
export const AFTER_CLOSE_HOURS = 'After Close Hours';

export const ALL = [
  ABSOLUTE_HOURS, OPERATION_HOURS, AFTER_OPEN_HOURS, AFTER_CLOSE_HOURS,
];

export const KRONOS_LABOR_PERIOD_TYPE_ENUM_INDEX = {
  ABSOLUTE_HOURS: 1,
  OPERATION_HOURS: 2,
  AFTER_OPEN_HOURS: 3,
  AFTER_CLOSE_HOURS: 4,
};

export const KRONOS_LABOR_PERIOD_TYPE_SELECT_OPTIONS = [
  {value: '', label: ''},
  {value: KRONOS_LABOR_PERIOD_TYPE_ENUM_INDEX.ABSOLUTE_HOURS, label: ABSOLUTE_HOURS},
  {value: KRONOS_LABOR_PERIOD_TYPE_ENUM_INDEX.OPERATION_HOURS, label: OPERATION_HOURS},
  {value: KRONOS_LABOR_PERIOD_TYPE_ENUM_INDEX.AFTER_OPEN_HOURS, label: AFTER_OPEN_HOURS},
  {value: KRONOS_LABOR_PERIOD_TYPE_ENUM_INDEX.AFTER_CLOSE_HOURS, label: AFTER_CLOSE_HOURS},
];
