export const SAME_AS_LABOR_PERIOD = 'Same As Selected Labor Period';
export const START_BEFORE_LABOR_PERIOD = 'Start Before Labor Period';
export const START_AFTER_LABOR_PERIOD = 'Start After Labor Period';

export const ALL = [
  SAME_AS_LABOR_PERIOD,
  START_BEFORE_LABOR_PERIOD,
  START_AFTER_LABOR_PERIOD,
];

export const KRONOS_LABOR_DISTRIBUTION_ENUM_INDEX = {
  SAME_AS_LABOR_PERIOD: 1,
  START_BEFORE_LABOR_PERIOD: 2,
  START_AFTER_LABOR_PERIOD: 3,
};

export const KRONOS_LABOR_DISTRIBUTION_SELECT_OPTIONS = [
  {value: '', label: ''},
  {value: KRONOS_LABOR_DISTRIBUTION_ENUM_INDEX.SAME_AS_LABOR_PERIOD, label: SAME_AS_LABOR_PERIOD},
  {value: KRONOS_LABOR_DISTRIBUTION_ENUM_INDEX.START_BEFORE_LABOR_PERIOD, label: START_BEFORE_LABOR_PERIOD},
  {value: KRONOS_LABOR_DISTRIBUTION_ENUM_INDEX.START_AFTER_LABOR_PERIOD, label: START_AFTER_LABOR_PERIOD},
];
