export const TIME_DEPENDENT = 'Time Dependent';
export const TIME_INDEPENDENT_BEFORE_TRAFFIC_STARTS = 'Time Independent; Allocate extra labor before traffic starts, then after traffic ends';
export const TIME_INDEPENDENT_AFTER_TRAFFIC_ENDS = 'Time Independent; Allocate extra labor after traffic ends, then before traffic starts';

export const ALL = [
  TIME_DEPENDENT,
  TIME_INDEPENDENT_BEFORE_TRAFFIC_STARTS,
  TIME_INDEPENDENT_AFTER_TRAFFIC_ENDS,
];

export const KRONOS_TIME_DEPENDENCY_ENUM_INDEX = {
  TIME_DEPENDENT: 1,
  TIME_INDEPENDENT_BEFORE_TRAFFIC_STARTS: 2,
  TIME_INDEPENDENT_AFTER_TRAFFIC_ENDS: 3,
};

export const KRONOS_TIME_DEPENDENCY_SELECT_OPTIONS = [
  {value: '', label: ''},
  {value: KRONOS_TIME_DEPENDENCY_ENUM_INDEX.TIME_DEPENDENT, label: TIME_DEPENDENT},
  {value: KRONOS_TIME_DEPENDENCY_ENUM_INDEX.TIME_INDEPENDENT_BEFORE_TRAFFIC_STARTS, label: TIME_INDEPENDENT_BEFORE_TRAFFIC_STARTS},
  {value: KRONOS_TIME_DEPENDENCY_ENUM_INDEX.TIME_INDEPENDENT_AFTER_TRAFFIC_ENDS, label: TIME_INDEPENDENT_AFTER_TRAFFIC_ENDS},
];
