export const VOLUME_DRIVER = 'Volume Driver';
export const CUSTOM_DRIVER = 'Custom Driver';
export const FIXED_FREQUENCY = 'Fixed Frequency';
export const FIXED_FREQUENCY_DAILY_VOLUME = 'Fixed Frequency by Daily Volume %';
export const STATIC_DRIVER = 'Static Driver';

export const ALL = [
  VOLUME_DRIVER,
  CUSTOM_DRIVER,
  FIXED_FREQUENCY,
  FIXED_FREQUENCY_DAILY_VOLUME,
  STATIC_DRIVER,
];

export const KRONOS_LABOR_DRIVER_TYPE_ENUM_INDEX = {
  VOLUME_DRIVER: 1,
  CUSTOM_DRIVER: 2,
  FIXED_FREQUENCY: 3,
  FIXED_FREQUENCY_DAILY_VOLUME: 4,
  STATIC_DRIVER: 5,
};

export const KRONOS_LABOR_DRIVER_TYPE_SELECT_OPTIONS = [
  {value: '', label: ''},
  {value: KRONOS_LABOR_DRIVER_TYPE_ENUM_INDEX.VOLUME_DRIVER, label: VOLUME_DRIVER},
  {value: KRONOS_LABOR_DRIVER_TYPE_ENUM_INDEX.CUSTOM_DRIVER, label: CUSTOM_DRIVER},
  {value: KRONOS_LABOR_DRIVER_TYPE_ENUM_INDEX.FIXED_FREQUENCY, label: FIXED_FREQUENCY},
  {value: KRONOS_LABOR_DRIVER_TYPE_ENUM_INDEX.FIXED_FREQUENCY_DAILY_VOLUME, label: FIXED_FREQUENCY_DAILY_VOLUME},
  {value: KRONOS_LABOR_DRIVER_TYPE_ENUM_INDEX.STATIC_DRIVER, label: STATIC_DRIVER},
];
