export const DISTRIBUTE_EVENLY_APPLY_ROUNDING = 'Distribute Evenly and Apply Rounding';
export const DISTRIBUTE_EVENLY_SPREAD_LEFT = 'Distribute Evenly and Spread Left';
export const DISTRIBUTE_EVENLY_SPREAD_RIGHT = 'Distribute Evenly and Spread Right';
export const DISTRIBUTE_TRAFFIC_PATTERN_COMPRESS = 'Distribute by Traffic Pattern and Compress';
export const DISTRIBUTE_TRAFFIC_PATTERN_TRUNCATE = 'Distribute by Traffic Pattern and Truncate';

export const ALL = [
  DISTRIBUTE_EVENLY_APPLY_ROUNDING,
  DISTRIBUTE_EVENLY_SPREAD_LEFT,
  DISTRIBUTE_EVENLY_SPREAD_RIGHT,
  DISTRIBUTE_TRAFFIC_PATTERN_COMPRESS,
  DISTRIBUTE_TRAFFIC_PATTERN_TRUNCATE,
];

export const KRONOS_TRAFFIC_PATTERN_ENUM_INDEX = {
  DISTRIBUTE_EVENLY_APPLY_ROUNDING: 1,
  DISTRIBUTE_EVENLY_SPREAD_LEFT: 2,
  DISTRIBUTE_EVENLY_SPREAD_RIGHT: 3,
  DISTRIBUTE_TRAFFIC_PATTERN_COMPRESS: 4,
  DISTRIBUTE_TRAFFIC_PATTERN_TRUNCATE: 5,
};

export const KRONOS_TRAFFIC_PATTERN_SELECT_OPTIONS = [
  {value: '', label: ''},
  {value: KRONOS_TRAFFIC_PATTERN_ENUM_INDEX.DISTRIBUTE_EVENLY_APPLY_ROUNDING, label: DISTRIBUTE_EVENLY_APPLY_ROUNDING},
  {value: KRONOS_TRAFFIC_PATTERN_ENUM_INDEX.DISTRIBUTE_EVENLY_SPREAD_LEFT, label: DISTRIBUTE_EVENLY_SPREAD_LEFT},
  {value: KRONOS_TRAFFIC_PATTERN_ENUM_INDEX.DISTRIBUTE_EVENLY_SPREAD_RIGHT, label: DISTRIBUTE_EVENLY_SPREAD_RIGHT},
  {value: KRONOS_TRAFFIC_PATTERN_ENUM_INDEX.DISTRIBUTE_TRAFFIC_PATTERN_COMPRESS, label: DISTRIBUTE_TRAFFIC_PATTERN_COMPRESS},
  {value: KRONOS_TRAFFIC_PATTERN_ENUM_INDEX.DISTRIBUTE_TRAFFIC_PATTERN_TRUNCATE, label: DISTRIBUTE_TRAFFIC_PATTERN_TRUNCATE},
];
