export const CLEAR_LOCATIONS_STANDARDS_EXPORT_LIST_FILTERS = 'CLEAR_LOCATIONS_STANDARDS_EXPORT_LIST_FILTERS';
export const CLEAR_LOCATIONS_STANDARDS_EXPORT_LIST_FILTERS_FULFILLED = `${CLEAR_LOCATIONS_STANDARDS_EXPORT_LIST_FILTERS}_FULFILLED`;

export function clearLocationsStandardsExportListFilters() {
  return {
    type: CLEAR_LOCATIONS_STANDARDS_EXPORT_LIST_FILTERS,
    payload: Promise.resolve(),
  };
}
