import {http} from '../../shared/services';
import {toExportUrl} from '../constants/DataSources';

export const CREATE_LOCATION_STANDARDS_EXPORT_REQUEST_BACKGROUND_JOB = 'CREATE_LOCATION_STANDARDS_EXPORT_REQUEST_BACKGROUND_JOB';
export const CREATE_LOCATION_STANDARDS_EXPORT_REQUEST_BACKGROUND_JOB_PENDING = `${CREATE_LOCATION_STANDARDS_EXPORT_REQUEST_BACKGROUND_JOB}_PENDING`;
export const CREATE_LOCATION_STANDARDS_EXPORT_REQUEST_BACKGROUND_JOB_FULFILLED = `${CREATE_LOCATION_STANDARDS_EXPORT_REQUEST_BACKGROUND_JOB}_FULFILLED`;
export const CREATE_LOCATION_STANDARDS_EXPORT_REQUEST_BACKGROUND_JOB_REJECTED = `${CREATE_LOCATION_STANDARDS_EXPORT_REQUEST_BACKGROUND_JOB}_REJECTED`;

export function createLocationStandardsExportRequestBackgroundJob(dataSource, exportRequestId) {
  const EXPORT_REQUEST_URL = dataSource ? `${toExportUrl(dataSource)}${exportRequestId}` : `locations-standards-export/export/${exportRequestId}`;

  return {
    type: CREATE_LOCATION_STANDARDS_EXPORT_REQUEST_BACKGROUND_JOB,
    payload: http.get(EXPORT_REQUEST_URL),
  };

}
