export const TOGGLE_SAVE_CACHED_GRID_CONFIG = 'TOGGLE_SAVE_CACHED_GRID_CONFIG';
export const TOGGLE_SAVE_CACHED_GRID_CONFIG_FULFILLED = `${TOGGLE_SAVE_CACHED_GRID_CONFIG}_FULFILLED`;
export const TOGGLE_SAVE_CACHED_GRID_CONFIG_REJECTED = `${TOGGLE_SAVE_CACHED_GRID_CONFIG}_REJECTED`;

export function toggleSaveCachedGridConfig() {
  return {
    type: TOGGLE_SAVE_CACHED_GRID_CONFIG,
    payload: Promise.resolve(),
  };
}
