import {http} from '../../shared/services';

export const INDUSTRY_STANDARDS_LOAD_INDUSTRY_STANDARD_NON_MOST_ELEMENT_DETAILS = 'INDUSTRY_STANDARDS/ LOAD_INDUSTRY_STANDARD_NON_MOST_ELEMENT_DETAILS';
export const INDUSTRY_STANDARDS_LOAD_INDUSTRY_STANDARD_NON_MOST_ELEMENT_DETAILS_REJECTED = `${INDUSTRY_STANDARDS_LOAD_INDUSTRY_STANDARD_NON_MOST_ELEMENT_DETAILS}_REJECTED`;
export const INDUSTRY_STANDARDS_LOAD_INDUSTRY_STANDARD_NON_MOST_ELEMENT_DETAILS_PENDING = `${INDUSTRY_STANDARDS_LOAD_INDUSTRY_STANDARD_NON_MOST_ELEMENT_DETAILS}_PENDING`;
export const INDUSTRY_STANDARDS_LOAD_INDUSTRY_STANDARD_NON_MOST_ELEMENT_DETAILS_FULFILLED = `${INDUSTRY_STANDARDS_LOAD_INDUSTRY_STANDARD_NON_MOST_ELEMENT_DETAILS}_FULFILLED`;

export function loadIndustryStandardNonMOSTElementDetails(IndustrySourceId, industryStandardId, industryStandardElementId) {
  return {
    type: INDUSTRY_STANDARDS_LOAD_INDUSTRY_STANDARD_NON_MOST_ELEMENT_DETAILS,
    payload: http.get(`industry-standards/${IndustrySourceId}/standards/${industryStandardId}/non-most/${industryStandardElementId}`),
  };
}
