export const CLOSE_IMPORT_LOCATION_MAPPING_VALIDATION_ERRORS = 'CLOSE_IMPORT_LOCATION_MAPPING_VALIDATION_ERRORS';

export function closeImportLocationMappingValidationErrors() {
  return {
    type: CLOSE_IMPORT_LOCATION_MAPPING_VALIDATION_ERRORS,
  };
}
