export const SHOW_IMPORT_LOCATION_MAPPING_VALIDATION_ERRORS = 'SHOW_IMPORT_LOCATION_MAPPING_VALIDATION_ERRORS';

export function showImportLocationMappingValidationErrors() {
  return {
    type: SHOW_IMPORT_LOCATION_MAPPING_VALIDATION_ERRORS,
  };
}
