export const RESET_STANDARDS_GRID_CONFIGURATION = 'RESET_STANDARDS_GRID_CONFIGURATION';
export const RESET_STANDARDS_GRID_CONFIGURATION_PENDING = `${RESET_STANDARDS_GRID_CONFIGURATION}_PENDING`;
export const RESET_STANDARDS_GRID_CONFIGURATION_REJECTED = `${RESET_STANDARDS_GRID_CONFIGURATION}_REJECTED`;
export const RESET_STANDARDS_GRID_CONFIGURATION_FULFILLED = `${RESET_STANDARDS_GRID_CONFIGURATION}_FULFILLED`;

export function resetStandardsGridConfiguration() {
  return {
    type: RESET_STANDARDS_GRID_CONFIGURATION,
    payload: Promise.resolve(),
  };
}
