import {generateReport, header, footer, styles} from './methodReport';
import {List, Map} from 'immutable';
const {describe, test, expect} = global;

const filingFieldsList = List([Map({
  id: 1,
  name: 'Area',
  options: [
    {value: '', label: ''},
    {value: 1, label: 'GTP'},
    {value: 2, label: 'BATCH WALL'},
    {value: 3, label: 'A+ PICK'},
    {value: 4, label: 'A+ STOCKING'},
    {value: 5, label: 'DECANT'},
    {value: 6, label: 'HIGHBAY'},
    {value: 7, label: 'SPECIAL HANDLING'},
    {value: 8, label: 'FREIGHT'},
    {value: 9, label: 'RECEIVING'},
  ],
}), Map({
  id: 2,
  name: 'Development Status',
  options: [{value: '', label: ''}],
})]);
const carharttDataTemplate = {
  id: 100081,
  revision: 1,
  hasRevisions: false,
  isPreviousRevision: false,
  currentInProcessRevision: 1,
  maxRevision: 0,
  name: 'ANCHOR CARTON',
  applicatorInstructions: null,
  details: {
    'name': 'ANCHOR CARTON',
    revision: 1,
    status: 'ReadyForQA',
    departmentId: 16,
    departmentName: 'FREIGHT',
    jobClassId: 7,
    laborCategoryId: 11,
    laborCategoryName: 'FREIGHT',
    classificationId: 8,
    classificationName: 'FREIGHT',
    allowanceId: null,
    allowanceName: null,
    attributeId: null,
    attributeName: null,
    applicatorName: 'wmcgregor@carhartt.com',
    lastEditorName: 'abundy@connorsllc.com',
    partFamilyId: null,
    allowanceFactor: null,
    machineAllowancePercent: null,
    normalTime: 4444.0,
    machineStandardTime: 0.0,
    manualStandardTime: 4444.0,
    statusComment: null,
    revisionComment: null,
    applicatorInstructions: null,
    fixed: false,
    effectiveStartDate: null,
    effectiveEndDate: null,
    filingFieldValues: [{
      'standardId': 100081,
      standardFilingFieldId: 1,
      standardFilingFieldOptionId: 8,
    }],
    standardStatusLogs: [{
      id: 37,
      oldStatus: 'Draft',
      newStatus: 'Ready for QA',
      comment: null,
      date: '11/15/18',
    }],
  },
  items: null,
  standardItems: [{
    type: 'StandardElementGroup',
    id: 2191,
    index: 1,
    name: 'LOCATE CARTON TO PALLET',
    normalTimeMeasurementUnits: 716.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2191,
    elementType: 'MOST',
    elementId: 103472,
    unitOfMeasureId: 131,
    unitOfMeasureName: 'FREIGHT_ANCHOR_CARTON',
    measuredTimeMeasurementUnits: 30.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: 'COMMENT - SCAN CARTON BARCODE', //comment to first element within a group
    elementStatus: 'ReadyForQA',
    id: 2201,
    index: 2,
    name: 'SCAN CARTON BARCODE',
    normalTimeMeasurementUnits: 30.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2191,
    elementType: 'MOST',
    elementId: 100047,
    unitOfMeasureId: 131,
    unitOfMeasureName: 'FREIGHT_ANCHOR_CARTON',
    measuredTimeMeasurementUnits: 156.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: true,
    comment: 'COMMENT - LOAD CARTON FROM CONVEYOR TO PALLET ON FLOOR', //comment to element within a group
    elementStatus: 'ReadyForQA',
    id: 2194,
    index: 3,
    name: 'LOAD CARTON FROM CONVEYOR TO PALLET ON FLOOR',
    normalTimeMeasurementUnits: 156.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2191,
    elementType: 'Timed',
    elementId: 103562,
    unitOfMeasureId: 131,
    unitOfMeasureName: 'FREIGHT_ANCHOR_CARTON',
    measuredTimeMeasurementUnits: 17.5,
    frequencyFormula: '2 *  FREIGHT_STEPS_TO_PALLET',
    frequencyValue: 26.0,
    internal: true,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2196,
    index: 4,
    name: 'WALK 1 STEP TO PALLET LOCATION AND BACK TO LANE',
    normalTimeMeasurementUnits: 455.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2191,
    elementType: 'MOST',
    elementId: 100875,
    unitOfMeasureId: 131,
    unitOfMeasureName: 'FREIGHT_ANCHOR_CARTON',
    measuredTimeMeasurementUnits: 50.0,
    frequencyFormula: ' FREIGHT_PCT_ANCHOR_CARTON_ADJUST',
    frequencyValue: 0.2,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2464,
    index: 5,
    name: 'ADJUST OTHER CARTON AS REQUIRED',
    normalTimeMeasurementUnits: 10.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2191,
    elementType: 'MOST',
    elementId: 103628,
    unitOfMeasureId: 131,
    unitOfMeasureName: 'FREIGHT_ANCHOR_CARTON',
    measuredTimeMeasurementUnits: 35.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: 'ReadyForQA',
    id: 2456,
    index: 6,
    name: 'SCAN PALLET BARCODE',
    normalTimeMeasurementUnits: 35.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2191,
    elementType: 'MOST',
    elementId: 100003,
    unitOfMeasureId: 131,
    unitOfMeasureName: 'FREIGHT_ANCHOR_CARTON',
    measuredTimeMeasurementUnits: 30.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: 'COMMENT - READ SCANNER TO SEE IF CARTON IS LAST CARTON ON ORDER', //comment to last element of group
    elementStatus: 'ReadyForQA',
    id: 2326,
    index: 7,
    name: 'READ SCANNER TO SEE IF CARTON IS LAST CARTON ON ORDER',
    normalTimeMeasurementUnits: 30.0,
  }, {
    type: 'StandardElementGroup',
    id: 2190,
    index: 8,
    name: 'LOCATE NEW PALLET TO LANE',
    normalTimeMeasurementUnits: 875.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2190,
    elementType: 'MOST',
    elementId: 103479,
    unitOfMeasureId: 148,
    unitOfMeasureName: 'FREIGHT_ANCHOR_NEW_PALLET',
    measuredTimeMeasurementUnits: 70.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2214,
    index: 9,
    name: 'GET AND TURN CARTON AS INDICATOR',
    normalTimeMeasurementUnits: 70.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2190,
    elementType: 'Timed',
    elementId: 103562,
    unitOfMeasureId: 148,
    unitOfMeasureName: 'FREIGHT_ANCHOR_NEW_PALLET',
    measuredTimeMeasurementUnits: 17.5,
    frequencyFormula: '2 * FREIGHT_STEPS_TO_RETRIEVE_EMPTY_PALLET ',
    frequencyValue: 30.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2197,
    index: 10,
    name: 'WALK TO RETRIEVE PALLET AND BACK',
    normalTimeMeasurementUnits: 525.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2190,
    elementType: 'MOST',
    elementId: 103600,
    unitOfMeasureId: 148,
    unitOfMeasureName: 'FREIGHT_ANCHOR_NEW_PALLET',
    measuredTimeMeasurementUnits: 220.0,
    frequencyFormula: ' 1 ',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: 'ReadyForQA',
    id: 2208,
    index: 11,
    name: 'OBTAIN EMPTY PALLET AND PLACE TO FLOOR',
    normalTimeMeasurementUnits: 220.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2190,
    elementType: 'MOST',
    elementId: 103472,
    unitOfMeasureId: 148,
    unitOfMeasureName: 'FREIGHT_ANCHOR_NEW_PALLET',
    measuredTimeMeasurementUnits: 30.0,
    frequencyFormula: '2',
    frequencyValue: 2.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2195,
    index: 12,
    name: 'SCAN PALLET BARCODE AND LANE LOCATION BARCODE',
    normalTimeMeasurementUnits: 60.0,
  }, {
    type: 'StandardElementGroup',
    id: 2192,
    index: 13,
    name: 'LOCATE PALLET TO STAGING AREA',
    normalTimeMeasurementUnits: 2633.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 103539,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 20.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2481,
    index: 14,
    name: 'PRESS N OPTION TO END PALLET',
    normalTimeMeasurementUnits: 20.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'Timed',
    elementId: 103562,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 17.5,
    frequencyFormula: 'FREIGHT_STEPS_TO_RETRIEVE_PALLET_JACK',
    frequencyValue: 18.0,
    internal: false,
    machineAllowance: false,
    comment: 'COMMENT - WALK TO RETRIEVE PALLET JACK',
    elementStatus: 'ReadyForQA',
    id: 2200,
    index: 15,
    name: 'WALK TO RETRIEVE PALLET JACK',
    normalTimeMeasurementUnits: 315.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 101023,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 21.0,
    frequencyFormula: 'FREIGHT_STEPS_TO_RETRIEVE_PALLET_JACK',
    frequencyValue: 18.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2511,
    index: 16,
    name: 'PUSH PALLET JACK BACK TO ANCHOR LOCATION',
    normalTimeMeasurementUnits: 378.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 103597,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 190.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: 'ReadyForQA',
    id: 2204,
    index: 17,
    name: 'PULL PALLET JACK OUT OF STACK',
    normalTimeMeasurementUnits: 190.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 103598,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 100.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: 'ReadyForQA',
    id: 2205,
    index: 18,
    name: 'PUSH PALLET JACK UNDER STACK',
    normalTimeMeasurementUnits: 100.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 103321,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 30.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2479,
    index: 19,
    name: 'SCAN PALLET BARCODE',
    normalTimeMeasurementUnits: 30.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 103599,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 40.0,
    frequencyFormula: '5',
    frequencyValue: 5.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: 'ReadyForQA',
    id: 2206,
    index: 20,
    name: 'RAISE PALLET WITH PALLET JACK ONE PUMP OF HANDLE',
    normalTimeMeasurementUnits: 200.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 103601,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 30.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: 'ReadyForQA',
    id: 2211,
    index: 21,
    name: 'INITIAL PUSH OR PULL OF FULL PALLET WITH PALLET JACK',
    normalTimeMeasurementUnits: 30.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 101023,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 21.0,
    frequencyFormula: 'FREIGHT_STEPS_TO_STAGE_ENDED_PALLET',
    frequencyValue: 26.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2360,
    index: 22,
    name: 'PUSH PALLET JACK TO STAGE PALLET',
    normalTimeMeasurementUnits: 546.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 103472,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 30.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2203,
    index: 23,
    name: 'SCAN STAGING AREA BARCODE',
    normalTimeMeasurementUnits: 30.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 103597,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 190.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2207,
    index: 24,
    name: 'PULL PALLET JACK OUT OF STACK',
    normalTimeMeasurementUnits: 190.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 101023,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 21.0,
    frequencyFormula: 'FREIGHT_STEPS_TO_RETURN_PALLET_JACK',
    frequencyValue: 9.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2361,
    index: 25,
    name: 'PUSH PALLET JACK BACK TO STORAGE LOCATION',
    normalTimeMeasurementUnits: 189.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'MOST',
    elementId: 103598,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 100.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2212,
    index: 26,
    name: 'PUSH PALLET JACK UNDER STACK',
    normalTimeMeasurementUnits: 100.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2192,
    elementType: 'Timed',
    elementId: 103562,
    unitOfMeasureId: 139,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    measuredTimeMeasurementUnits: 17.5,
    frequencyFormula: 'FREIGHT_STEPS_TO_RETRIEVE_PALLET_JACK',
    frequencyValue: 18.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2513,
    index: 27,
    name: 'WALK TO RETURN TO LANE',
    normalTimeMeasurementUnits: 315.0,
  }, {
    type: 'StandardElementGroup',
    id: 2369,
    index: 28,
    name: 'CANADA OVERLAY',
    normalTimeMeasurementUnits: 0.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2369,
    elementType: 'MOST',
    elementId: 103613,
    unitOfMeasureId: 140,
    unitOfMeasureName: 'FREIGHT_ANCHOR_CANADA_CARTON',
    measuredTimeMeasurementUnits: 180.0,
    frequencyFormula: 'FREIGHT_PCT_OF_CARTONS_NEEDING_OVERLAY',
    frequencyValue: 0.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2370,
    index: 29,
    name: 'OBTAIN OVERLAY AND ATTACH TO CARTON',
    normalTimeMeasurementUnits: 0.0,
  }, {
    type: 'StandardElementGroup',
    id: 2462,
    index: 30,
    name: 'EXCEPTIONS**',
    normalTimeMeasurementUnits: 220.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 2462,
    elementType: 'MOST',
    elementId: 103241,
    unitOfMeasureId: 131,
    unitOfMeasureName: 'FREIGHT_ANCHOR_CARTON',
    measuredTimeMeasurementUnits: 220.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'ReadyForQA',
    id: 2463,
    index: 31,
    name: 'APPLY TAPE TO CARTON',
    normalTimeMeasurementUnits: 220.0,
  }],
  standardUnitsOfMeasure: [{
    id: 1252,
    unitOfMeasureName: 'FREIGHT_ANCHOR_CANADA_CARTON',
    totalManualNormalTimeMeasurementUnits: 0.0,
    totalMachineNormalTimeMeasurementUnits: 0.0,
    totalNormalTimeMeasurementUnits: 0.0,
    totalManualStandardTimeMeasurementUnits: 0.0,
    totalMachineStandardTimeMeasurementUnits: 0.0,
    totalStandardTimeMeasurementUnits: 0.0,
  }, {
    id: 1266,
    unitOfMeasureName: 'FREIGHT_ANCHOR_CARTON',
    totalManualNormalTimeMeasurementUnits: 936.0,
    totalMachineNormalTimeMeasurementUnits: 0.0,
    totalNormalTimeMeasurementUnits: 936.0,
    totalManualStandardTimeMeasurementUnits: 936.0,
    totalMachineStandardTimeMeasurementUnits: 0.0,
    totalStandardTimeMeasurementUnits: 936.0,
  }, {
    id: 1267,
    unitOfMeasureName: 'FREIGHT_ANCHOR_STAGE_PALLET',
    totalManualNormalTimeMeasurementUnits: 2633.0,
    totalMachineNormalTimeMeasurementUnits: 4242.0,
    totalNormalTimeMeasurementUnits: 2633.0,
    totalManualStandardTimeMeasurementUnits: 2633.0,
    totalMachineStandardTimeMeasurementUnits: 4242.0,
    totalStandardTimeMeasurementUnits: 2633.0,
  }, {
    id: 1276,
    unitOfMeasureName: 'FREIGHT_ANCHOR_NEW_PALLET',
    totalManualNormalTimeMeasurementUnits: 875.0,
    totalMachineNormalTimeMeasurementUnits: 0.0,
    totalNormalTimeMeasurementUnits: 875.0,
    totalManualStandardTimeMeasurementUnits: 875.0,
    totalMachineStandardTimeMeasurementUnits: 0.0,
    totalStandardTimeMeasurementUnits: 875.0,
  }],
  characteristics: [{
    id: 143,
    name: 'FREIGHT_STEPS_TO_PALLET',
    definition: 'Average number of steps to pallet from lane.',
    defaultValue: 13.0,
  }, {
    id: 144,
    name: 'FREIGHT_STEPS_TO_RETRIEVE_EMPTY_PALLET',
    definition: 'Average number of steps needed to retrieve empty pallet.',
    defaultValue: 15.0,
  }, {
    id: 146,
    name: 'FREIGHT_STEPS_TO_RETRIEVE_PALLET_JACK',
    definition: 'Average number of steps to retrieve a pallet jack.',
    defaultValue: 18.0,
  }, {
    id: 145,
    name: 'FREIGHT_STEPS_TO_STAGE_ENDED_PALLET',
    definition: 'Average number of steps needed to stage a completed pallet using a pallet jack.',
    defaultValue: 26.0,
  }, {
    id: 147,
    name: 'FREIGHT_STEPS_TO_RETURN_PALLET_JACK',
    definition: 'Average number of steps to return pallet jack after use.',
    defaultValue: 9.0,
  }, {
    id: 157,
    name: 'FREIGHT_PCT_OF_CARTONS_NEEDING_OVERLAY',
    definition: 'Percentage of cartons that require overlay.',
    defaultValue: 0.0,
  }, {
    id: 167,
    name: 'FREIGHT_PCT_ANCHOR_CARTON_ADJUST',
    definition: 'Percent of cases placed to anchor pallet that requires another carton to be adjusted, moved, or floated. ',
    defaultValue: 0.2,
  }],
  elementsForReport: [{
    elementId: 100003,
    standardElementId: null,
    number: 1,
    description: 'READ VAS INSTRUCTION FROM RF DEVICE',
    sequenceModel: 'A0 B0 G0 A0 B0 P0 T3 A0 B0 P0 A0',
    adjustedMeasuredTimeMeasurementUnits: 0,
  }, {
    elementId: 100047,
    standardElementId: null,
    number: 1,
    description: 'GRAB CASE ON CONVEYOR AND SLIDE OFF',
    sequenceModel: 'A1 B0 G3 M3 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 70.0,
  }, {
    elementId: 100047,
    standardElementId: null,
    number: 2,
    description: 'READ SCREEN FOR PALLET LOCATION',
    sequenceModel: 'A0 B0 G0 A0 B0 P0 T1 A0 B0 P0 A0',
    adjustedMeasuredTimeMeasurementUnits: 10.0,
  }, {
    elementId: 100047,
    standardElementId: null,
    number: 3,
    description: 'PICK UP CASE FROM CONVEYOR AND POSITION ON PALLET',
    sequenceModel: 'A0 B0 G0 A1 (B3) P6 A0 (0.200)',
    adjustedMeasuredTimeMeasurementUnits: 76.0,
  }, {
    elementId: 100875,
    standardElementId: null,
    number: 1,
    description: 'ADJUST BOX',
    sequenceModel: 'A1 B0 G1 M3 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 50.0,
  }, {
    elementId: 101023,
    standardElementId: null,
    number: 1,
    description: 'PUSH CART 1 STEP',
    sequenceModel: null,
    adjustedMeasuredTimeMeasurementUnits: 21.0,
  }, {
    elementId: 103241,
    standardElementId: null,
    number: 1,
    description: 'GET TAPE AND APPLY',
    sequenceModel: 'A1 B3 G1 M10 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 150.0,
  }, {
    elementId: 103241,
    standardElementId: null,
    number: 2,
    description: 'TEAR TAPE',
    sequenceModel: 'A1 B0 G1 M3 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 50.0,
  }, {
    elementId: 103241,
    standardElementId: null,
    number: 3,
    description: 'PUT TAPE ASIDE',
    sequenceModel: 'A0 B0 G0 A1 B0 P1 A0',
    adjustedMeasuredTimeMeasurementUnits: 20.0,
  }, {
    elementId: 103321,
    standardElementId: null,
    number: 1,
    description: 'SCAN BARCODE',
    sequenceModel: 'A0 B0 G0 M1 X1 I1 A0',
    adjustedMeasuredTimeMeasurementUnits: 30.0,
  }, {
    elementId: 103472,
    standardElementId: null,
    number: 1,
    description: 'SCAN BARCODE WITH GRASP OF UPC SIMO',
    sequenceModel: 'A1 B0 <G1> M1 X1 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 30.0,
  }, {
    elementId: 103479,
    standardElementId: null,
    number: 1,
    description: 'GET AND TURN CASE 180 DEGREES',
    sequenceModel: 'A1 B0 G3 M3 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 70.0,
  }, {
    elementId: 103539,
    standardElementId: null,
    number: 1,
    description: 'PRESS BUTTON',
    sequenceModel: 'A0 B0 G1 M1 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 20.0,
  }, {
    elementId: 103562,
    standardElementId: null,
    number: 1,
    description: 'WALK 1 STEP',
    sequenceModel: null,
    adjustedMeasuredTimeMeasurementUnits: 17.5,
  }, {
    elementId: 103597,
    standardElementId: null,
    number: 1,
    description: 'OBTAIN HANDLE OF PALLET JACK AND LOWER PALLET JACK SIMO',
    sequenceModel: 'A1 B0 (G1) M1 X0 I0 A0 (2.000)',
    adjustedMeasuredTimeMeasurementUnits: 40.0,
  }, {
    elementId: 103597,
    standardElementId: null,
    number: 2,
    description: 'PULL PALLET JACK STEERING HANDLE BACK',
    sequenceModel: 'A0 B0 G0 M3 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 30.0,
  }, {
    elementId: 103597,
    standardElementId: null,
    number: 3,
    description: 'WALK 4 STEPS BACK WITH PALLET JACK IN 2 STAGES ',
    sequenceModel: 'A6 B0 G0 M6 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 120.0,
  }, {
    elementId: 103598,
    standardElementId: null,
    number: 1,
    description: 'PUSH PALLET JACK UNDER PALLET IN 2 STAGES AND 2 STEPS NO GET',
    sequenceModel: 'A3 B0 G0 M6 X0 I1 A0',
    adjustedMeasuredTimeMeasurementUnits: 100.0,
  }, {
    elementId: 103599,
    standardElementId: null,
    number: 1,
    description: 'PULL DOWN ON HANDLE AND RETURN HANDLE NO GET',
    sequenceModel: 'A0 B0 G0 M3 X0 I0 A1',
    adjustedMeasuredTimeMeasurementUnits: 40.0,
  }, {
    elementId: 103600,
    standardElementId: null,
    number: 1,
    description: 'OBTAIN EMPTY PALLET FROM STACK IN 2 STAGES BENDING 50% OF TIME',
    sequenceModel: 'A1 B3 G3 M6 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 130.0,
  }, {
    elementId: 103600,
    standardElementId: null,
    number: 2,
    description: 'PLACE PALLET TO FLOOR',
    sequenceModel: 'A0 B0 G0 A0 B6 P3 A0',
    adjustedMeasuredTimeMeasurementUnits: 90.0,
  }, {
    elementId: 103601,
    standardElementId: null,
    number: 1,
    description: 'INITIAL PUSH OR PULL OF PALLET JACK WITH FULL PALLET',
    sequenceModel: 'A0 B0 G0 M3 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 30.0,
  }, {
    elementId: 103613,
    standardElementId: null,
    number: 1,
    description: 'OBTAIN OVERLAY',
    sequenceModel: 'A3 B0 G1 A3 B0 P1 A0',
    adjustedMeasuredTimeMeasurementUnits: 80.0,
  }, {
    elementId: 103613,
    standardElementId: null,
    number: 2,
    description: 'REMOVE BACKING AND DISPOSE OF BACKING',
    sequenceModel: 'A1 B0 G3 A1 B0 P1 A0',
    adjustedMeasuredTimeMeasurementUnits: 60.0,
  }, {
    elementId: 103613,
    standardElementId: null,
    number: 3,
    description: 'ATTACH OVERLAY TO CARTON WITH NO GET',
    sequenceModel: 'A0 B0 G0 A1 B0 P3 A0',
    adjustedMeasuredTimeMeasurementUnits: 40.0,
  }, {
    elementId: 103628,
    standardElementId: null,
    number: 1,
    description: 'SCAN BARCODE WITH BEND NO GET OF SCANNER',
    sequenceModel: 'A1 (B3) G0 M1 X0 I0 A0 (0.500)',
    adjustedMeasuredTimeMeasurementUnits: 35.0,
  }],
  defaultCharacteristicSetName: 'Characteristic Set FREIGHT',
};
const lbrandsDataTemplate = {
  id: 100026,
  revision: 1,
  hasRevisions: false,
  isPreviousRevision: false,
  currentInProcessRevision: 1,
  maxRevision: 0,
  name: 'DC4 - Bra Picking',
  applicatorInstructions: null,
  details: {
    name: 'DC4 - Bra Picking',
    revision: 1,
    status: 'Draft',
    departmentId: 8,
    departmentName: 'Picking',
    jobClassId: null,
    laborCategoryId: null,
    laborCategoryName: null,
    classificationId: null,
    classificationName: null,
    allowanceId: null,
    allowanceName: null,
    attributeId: null,
    attributeName: null,
    applicatorName: 'mmyers@lb.com',
    lastEditorName: 'mmyers@lb.com',
    partFamilyId: null,
    allowanceFactor: null,
    machineAllowancePercent: null,
    normalTime: 1158.7388888888891,
    machineStandardTime: 0.0,
    manualStandardTime: 1158.7388888888891,
    statusComment: null,
    revisionComment: null,
    applicatorInstructions: null,
    fixed: true,
    effectiveStartDate: null,
    effectiveEndDate: null,
    filingFieldValues: [],
    standardStatusLogs: [],
  },
  items: null,
  standardItems: [{
    type: 'StandardElementGroup',
    id: 1114,
    index: 1,
    name: '***NEW LABEL WORK***',
    normalTimeMeasurementUnits: 370.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1114,
    elementType: 'MOST',
    elementId: 100089,
    unitOfMeasureId: 120,
    unitOfMeasureName: 'Bra Pick - First Pick Carton',
    measuredTimeMeasurementUnits: 250.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: 'Draft',
    id: 1142,
    index: 2,
    name: 'Get carton and Apply Label - First Pick',
    normalTimeMeasurementUnits: 250.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1114,
    elementType: 'MOST',
    elementId: 100006,
    unitOfMeasureId: 120,
    unitOfMeasureName: 'Bra Pick - First Pick Carton',
    measuredTimeMeasurementUnits: 120.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'Draft',
    id: 1120,
    index: 3,
    name: 'Scan Barcode and Read RF (Get & Aside Scanner)',
    normalTimeMeasurementUnits: 120.0,
  }, {
    type: 'StandardElementGroup',
    id: 1115,
    index: 4,
    name: '***PROGRESSIVE CARTON WORK***',
    normalTimeMeasurementUnits: 218.66666666666669,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1115,
    elementType: 'Timed',
    elementId: 100082,
    unitOfMeasureId: 122,
    unitOfMeasureName: 'Bra Pick - Progressive Carton',
    measuredTimeMeasurementUnits: 17.5,
    frequencyFormula: '6/ DC4_AVG_CARTON_PER_GET_PREV_SECTION ',
    frequencyValue: 1.2,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'Production',
    id: 1178,
    index: 5,
    name: 'Walk to get cartons from previous section',
    normalTimeMeasurementUnits: 21.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1115,
    elementType: 'MOST',
    elementId: 512,
    unitOfMeasureId: 122,
    unitOfMeasureName: 'Bra Pick - Progressive Carton',
    measuredTimeMeasurementUnits: 60.0,
    frequencyFormula: '1/ DC4_AVG_CARTON_PER_GET_PREV_SECTION ',
    frequencyValue: 0.2,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'Production',
    id: 1179,
    index: 6,
    name: 'Collect multiple Cartons',
    normalTimeMeasurementUnits: 12.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1115,
    elementType: 'MOST',
    elementId: null,
    unitOfMeasureId: 122,
    unitOfMeasureName: 'Bra Pick - Progressive Carton',
    measuredTimeMeasurementUnits: 20.0,
    frequencyFormula: '6/ DC4_AVG_CARTON_PER_GET_PREV_SECTION ',
    frequencyValue: 1.2,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1180,
    index: 7,
    name: 'Move cartons down line',
    normalTimeMeasurementUnits: 24.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1115,
    elementType: 'Estimate',
    elementId: null,
    unitOfMeasureId: 122,
    unitOfMeasureName: 'Bra Pick - Progressive Carton',
    measuredTimeMeasurementUnits: 41.666666666666671,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1121,
    index: 8,
    name: 'Walk to get next carton',
    normalTimeMeasurementUnits: 41.666666666666671,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1115,
    elementType: 'MOST',
    elementId: 100006,
    unitOfMeasureId: 122,
    unitOfMeasureName: 'Bra Pick - Progressive Carton',
    measuredTimeMeasurementUnits: 120.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'Draft',
    id: 1122,
    index: 9,
    name: 'Scan Barcode and Read RF (Get & Aside Scanner)',
    normalTimeMeasurementUnits: 120.0,
  }, {
    type: 'StandardElementGroup',
    id: 1116,
    index: 10,
    name: '***PICK REACHES***',
    normalTimeMeasurementUnits: 127.875,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1116,
    elementType: 'Estimate',
    elementId: null,
    unitOfMeasureId: 99,
    unitOfMeasureName: 'Dynamic Travel',
    measuredTimeMeasurementUnits: 0.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1123,
    index: 11,
    name: 'Travel to first pick location',
    normalTimeMeasurementUnits: 0.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1116,
    elementType: 'MOST',
    elementId: 3159,
    unitOfMeasureId: 122,
    unitOfMeasureName: 'Bra Pick - Progressive Carton',
    measuredTimeMeasurementUnits: 10.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: true,
    machineAllowance: false,
    comment: null,
    elementStatus: 'Production',
    id: 1124,
    index: 12,
    name: 'READ 1 DIGIT (NO GET, PUT, OR ASIDE)',
    normalTimeMeasurementUnits: 0.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1116,
    elementType: 'MOST',
    elementId: null,
    unitOfMeasureId: 123,
    unitOfMeasureName: 'Bra Pick - Reach',
    measuredTimeMeasurementUnits: 50.0,
    frequencyFormula: ' DC4_AVG_BAGS_PER_BRA_CASE/  DC4_AVG_BRAS_PER_CASE ',
    frequencyValue: 0.0375,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1126,
    index: 13,
    name: 'Open Plastic Bag',
    normalTimeMeasurementUnits: 1.875,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1116,
    elementType: 'MOST',
    elementId: null,
    unitOfMeasureId: 123,
    unitOfMeasureName: 'Bra Pick - Reach',
    measuredTimeMeasurementUnits: 36.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1125,
    index: 14,
    name: 'Get Reach',
    normalTimeMeasurementUnits: 36.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1116,
    elementType: 'MOST',
    elementId: 100087,
    unitOfMeasureId: 121,
    unitOfMeasureName: 'Bra Pick - Location',
    measuredTimeMeasurementUnits: 20.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'Draft',
    id: 1127,
    index: 15,
    name: 'Press button',
    normalTimeMeasurementUnits: 20.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1116,
    elementType: 'MOST',
    elementId: 2595,
    unitOfMeasureId: 122,
    unitOfMeasureName: 'Bra Pick - Progressive Carton',
    measuredTimeMeasurementUnits: 30.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'Production',
    id: 1128,
    index: 16,
    name: 'Walk product to carton',
    normalTimeMeasurementUnits: 30.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1116,
    elementType: 'MOST',
    elementId: null,
    unitOfMeasureId: 122,
    unitOfMeasureName: 'Bra Pick - Progressive Carton',
    measuredTimeMeasurementUnits: 40.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1279,
    index: 17,
    name: 'Place Reaches in carton (includes smooth time)',
    normalTimeMeasurementUnits: 40.0,
  }, {
    type: 'StandardElementGroup',
    id: 1117,
    index: 18,
    name: '***PASS CARTON***',
    normalTimeMeasurementUnits: 71.6,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1117,
    elementType: 'MOST',
    elementId: 2698,
    unitOfMeasureId: 122,
    unitOfMeasureName: 'Bra Pick - Progressive Carton',
    measuredTimeMeasurementUnits: 50.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'Production',
    id: 1131,
    index: 19,
    name: 'GRASP, WITHIN REACH | MOVE > 12 IN',
    normalTimeMeasurementUnits: 50.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1117,
    elementType: 'MOST',
    elementId: null,
    unitOfMeasureId: 122,
    unitOfMeasureName: 'Bra Pick - Progressive Carton',
    measuredTimeMeasurementUnits: 120.0,
    frequencyFormula: ' DC4_PCT_BRA_PASS_NO_PICK ',
    frequencyValue: 0.18,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1181,
    index: 20,
    name: 'Pass No Pick',
    normalTimeMeasurementUnits: 21.599999999999998,
  }, {
    type: 'StandardElementGroup',
    id: 1118,
    index: 21,
    name: '***CARTON DONE WORK***',
    normalTimeMeasurementUnits: 360.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1118,
    elementType: 'MOST',
    elementId: 100090,
    unitOfMeasureId: 119,
    unitOfMeasureName: 'Bra Pick - Carton Done',
    measuredTimeMeasurementUnits: 300.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: null,
    elementStatus: 'Draft',
    id: 1276,
    index: 22,
    name: 'Close Completed Carton - DC4 Picking',
    normalTimeMeasurementUnits: 300.0,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1118,
    elementType: 'MOST',
    elementId: null,
    unitOfMeasureId: 119,
    unitOfMeasureName: 'Bra Pick - Carton Done',
    measuredTimeMeasurementUnits: 60.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1147,
    index: 23,
    name: 'Push carton off',
    normalTimeMeasurementUnits: 60.0,
  }, {
    type: 'StandardElementGroup',
    id: 1119,
    index: 24,
    name: '***NON CYCLICAL ACTIVITIES***',
    normalTimeMeasurementUnits: 10.597222222222221,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1119,
    elementType: 'Estimate',
    elementId: null,
    unitOfMeasureId: 123,
    unitOfMeasureName: 'Bra Pick - Reach',
    measuredTimeMeasurementUnits: 277.77777777777777,
    frequencyFormula: '1/ DC4_AVG_BRAS_PER_CASE ',
    frequencyValue: 0.0125,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1182,
    index: 25,
    name: 'SKU Check',
    normalTimeMeasurementUnits: 3.4722222222222223,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1119,
    elementType: 'MOST',
    elementId: null,
    unitOfMeasureId: 123,
    unitOfMeasureName: 'Bra Pick - Reach',
    measuredTimeMeasurementUnits: 120.0,
    frequencyFormula: '1/ DC4_AVG_BRAS_PER_CASE ',
    frequencyValue: 0.0125,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1136,
    index: 26,
    name: 'Discard Bra Box',
    normalTimeMeasurementUnits: 1.5,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1119,
    elementType: 'MOST',
    elementId: null,
    unitOfMeasureId: 123,
    unitOfMeasureName: 'Bra Pick - Reach',
    measuredTimeMeasurementUnits: 40.0,
    frequencyFormula: ' DC4_AVG_BAGS_PER_BRA_CASE / DC4_AVG_BRAS_PER_CASE ',
    frequencyValue: 0.0375,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1281,
    index: 27,
    name: 'Discard Bra Balls',
    normalTimeMeasurementUnits: 1.5,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1119,
    elementType: 'MOST',
    elementId: null,
    unitOfMeasureId: 123,
    unitOfMeasureName: 'Bra Pick - Reach',
    measuredTimeMeasurementUnits: 110.0,
    frequencyFormula: ' DC4_AVG_BAGS_PER_BRA_CASE / DC4_AVG_BRAS_PER_CASE ',
    frequencyValue: 0.0375,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1137,
    index: 28,
    name: 'Discard Bra Bags',
    normalTimeMeasurementUnits: 4.125,
  }, {
    type: 'StandardElement',
    standardElementGroupId: 1119,
    elementType: 'Estimate',
    elementId: null,
    unitOfMeasureId: 123,
    unitOfMeasureName: 'Bra Pick - Reach',
    measuredTimeMeasurementUnits: 0.0,
    frequencyFormula: '1',
    frequencyValue: 1.0,
    internal: false,
    machineAllowance: false,
    comment: '',
    elementStatus: null,
    id: 1138,
    index: 29,
    name: 'Wait for Replenishment',
    normalTimeMeasurementUnits: 0.0,
  }],
  standardUnitsOfMeasure: [{
    id: 158,
    unitOfMeasureName: 'Dynamic Travel',
    totalManualNormalTimeMeasurementUnits: 0.0,
    totalMachineNormalTimeMeasurementUnits: 0.0,
    totalNormalTimeMeasurementUnits: 0.0,
    totalManualStandardTimeMeasurementUnits: 0.0,
    totalMachineStandardTimeMeasurementUnits: 0.0,
    totalStandardTimeMeasurementUnits: 0.0,
  }, {
    id: 159,
    unitOfMeasureName: 'Bra Pick - Progressive Carton',
    totalManualNormalTimeMeasurementUnits: 360.26666666666671,
    totalMachineNormalTimeMeasurementUnits: 0.0,
    totalNormalTimeMeasurementUnits: 360.26666666666671,
    totalManualStandardTimeMeasurementUnits: 360.26666666666671,
    totalMachineStandardTimeMeasurementUnits: 0.0,
    totalStandardTimeMeasurementUnits: 360.26666666666671,
  }, {
    id: 160,
    unitOfMeasureName: 'Bra Pick - Reach',
    totalManualNormalTimeMeasurementUnits: 48.472222222222221,
    totalMachineNormalTimeMeasurementUnits: 0.0,
    totalNormalTimeMeasurementUnits: 48.472222222222221,
    totalManualStandardTimeMeasurementUnits: 48.472222222222221,
    totalMachineStandardTimeMeasurementUnits: 0.0,
    totalStandardTimeMeasurementUnits: 48.472222222222221,
  }, {
    id: 161,
    unitOfMeasureName: 'Bra Pick - First Pick Carton',
    totalManualNormalTimeMeasurementUnits: 370.0,
    totalMachineNormalTimeMeasurementUnits: 0.0,
    totalNormalTimeMeasurementUnits: 370.0,
    totalManualStandardTimeMeasurementUnits: 370.0,
    totalMachineStandardTimeMeasurementUnits: 0.0,
    totalStandardTimeMeasurementUnits: 370.0,
  }, {
    id: 162,
    unitOfMeasureName: 'Bra Pick - Carton Done',
    totalManualNormalTimeMeasurementUnits: 360.0,
    totalMachineNormalTimeMeasurementUnits: 0.0,
    totalNormalTimeMeasurementUnits: 360.0,
    totalManualStandardTimeMeasurementUnits: 360.0,
    totalMachineStandardTimeMeasurementUnits: 0.0,
    totalStandardTimeMeasurementUnits: 360.0,
  }, {
    id: 173,
    unitOfMeasureName: 'Bra Pick - Location',
    totalManualNormalTimeMeasurementUnits: 20.0,
    totalMachineNormalTimeMeasurementUnits: 0.0,
    totalNormalTimeMeasurementUnits: 20.0,
    totalManualStandardTimeMeasurementUnits: 20.0,
    totalMachineStandardTimeMeasurementUnits: 0.0,
    totalStandardTimeMeasurementUnits: 20.0,
  }],
  characteristics: [{
    id: 91,
    name: 'DC4_AVG_BRAS_PER_CASE',
    definition: '',
    defaultValue: 80.0,
  }, {
    id: 92,
    name: 'DC4_AVG_BAGS_PER_BRA_CASE',
    definition: '',
    defaultValue: 3.0,
  }, {
    id: 93,
    name: 'DC4_AVG_CARTON_PER_GET_PREV_SECTION',
    definition: '',
    defaultValue: 5.0,
  }, {
    id: 95,
    name: 'DC4_PCT_BRA_PASS_NO_PICK',
    definition: '',
    defaultValue: 0.18,
  }],
  elementsForReport: [{
    elementId: null,
    standardElementId: 1125,
    number: 1,
    description: 'get units',
    sequenceModel: 'A1 B0 G1 A0 B0 P0 A0',
    adjustedMeasuredTimeMeasurementUnits: 18.0,
  }, {
    elementId: null,
    standardElementId: 1126,
    number: 1,
    description: 'Grasp bag and rip open',
    sequenceModel: 'A1 B0 G1 M3 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 50.0,
  }, {
    elementId: null,
    standardElementId: 1136,
    number: 1,
    description: 'Discard box',
    sequenceModel: 'A3 B0 G3 A3 B0 P0 A3',
    adjustedMeasuredTimeMeasurementUnits: 120.0,
  }, {
    elementId: null,
    standardElementId: 1137,
    number: 1,
    description: 'Discard bag',
    sequenceModel: 'A3 B0 G1 A3 B0 P1 A3',
    adjustedMeasuredTimeMeasurementUnits: 110.0,
  }, {
    elementId: null,
    standardElementId: 1147,
    number: 1,
    description: 'Default MOST Analysis Step',
    sequenceModel: 'A1 B0 G1 M3 X0 I0 A1',
    adjustedMeasuredTimeMeasurementUnits: 60.0,
  }, {
    elementId: null,
    standardElementId: 1180,
    number: 1,
    description: 'Move 1 step',
    sequenceModel: 'A1 B0 G0 M1 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 20.0,
  }, {
    elementId: null,
    standardElementId: 1181,
    number: 1,
    description: 'Read PTL System',
    sequenceModel: 'A3 B0 G0 A0 B0 P0 T1 A0 B0 P0 A3',
    adjustedMeasuredTimeMeasurementUnits: 70.0,
  }, {
    elementId: null,
    standardElementId: 1279,
    number: 1,
    description: 'Put within reach',
    sequenceModel: 'A0 B0 G0 A1 B0 P3 A0',
    adjustedMeasuredTimeMeasurementUnits: 40.0,
  }, {
    elementId: null,
    standardElementId: 1281,
    number: 1,
    description: 'Get bra bags and discard',
    sequenceModel: 'A1 B0 G1 A1 B0 P1 A0',
    adjustedMeasuredTimeMeasurementUnits: 40.0,
  }, {
    elementId: null,
    standardElementId: 1125,
    number: 2,
    description: 'additional get time',
    sequenceModel: 'A1 B0 G3 A0 B0 P0 A0',
    adjustedMeasuredTimeMeasurementUnits: 4.0,
  }, {
    elementId: null,
    standardElementId: 1181,
    number: 2,
    description: 'Push Carton Down Line',
    sequenceModel: 'A1 B0 G0 M3 X0 I0 A1',
    adjustedMeasuredTimeMeasurementUnits: 50.0,
  }, {
    elementId: null,
    standardElementId: 1125,
    number: 3,
    description: 'put on arm',
    sequenceModel: 'A0 B0 G0 A1 B0 P1 A0',
    adjustedMeasuredTimeMeasurementUnits: 14.0,
  }, {
    elementId: 512,
    standardElementId: null,
    number: 1,
    description: 'GET, WITHIN REACH | PUT, WITHIN REACH',
    sequenceModel: 'A1 B0 G3 A1 B0 P1 A0',
    adjustedMeasuredTimeMeasurementUnits: 60.0,
  }, {
    elementId: 2595,
    standardElementId: null,
    number: 1,
    description: 'TOSS or KEEP, 1-2 STEPS',
    sequenceModel: 'A0 B0 G0 A3 B0 P0 A0',
    adjustedMeasuredTimeMeasurementUnits: 30.0,
  }, {
    elementId: 2698,
    standardElementId: null,
    number: 1,
    description: 'GRASP, WITHIN REACH | MOVE > 12 IN',
    sequenceModel: 'A1 B0 G1 M3 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 50.0,
  }, {
    elementId: 3159,
    standardElementId: null,
    number: 1,
    description: 'READ 1 DIGIT (NO GET, PUT, OR ASIDE)',
    sequenceModel: 'A0 B0 G0 A0 B0 P0 T1 A0 B0 P0 A0',
    adjustedMeasuredTimeMeasurementUnits: 10.0,
  }, {
    elementId: 100006,
    standardElementId: null,
    number: 1,
    description: 'Get Scanner and Scan Barcode',
    sequenceModel: 'A1 B0 G1 A1 B0 P3 A0',
    adjustedMeasuredTimeMeasurementUnits: 60.0,
  }, {
    elementId: 100006,
    standardElementId: null,
    number: 2,
    description: 'Read Suggested Putaway Location',
    sequenceModel: 'A0 B0 G0 A1 B0 P0 T3 A0 B0 P0 A0',
    adjustedMeasuredTimeMeasurementUnits: 40.0,
  }, {
    elementId: 100006,
    standardElementId: null,
    number: 3,
    description: 'Set Scanner Aside',
    sequenceModel: 'A0 B0 G0 A1 B0 P1 A0',
    adjustedMeasuredTimeMeasurementUnits: 20.0,
  }, {
    elementId: 100082,
    standardElementId: null,
    number: 1,
    description: 'WALK 1 STEP',
    sequenceModel: null,
    adjustedMeasuredTimeMeasurementUnits: 17.5,
  }, {
    elementId: 100087,
    standardElementId: null,
    number: 1,
    description: 'Press 1 Button',
    sequenceModel: 'A0 B0 G0 A1 B0 P1 A0',
    adjustedMeasuredTimeMeasurementUnits: 20.0,
  }, {
    elementId: 100089,
    standardElementId: null,
    number: 1,
    description: 'Get carton from overhead line',
    sequenceModel: 'A1 B0 G1 A1 B0 P1 A0',
    adjustedMeasuredTimeMeasurementUnits: 40.0,
  }, {
    elementId: 100089,
    standardElementId: null,
    number: 2,
    description: 'Get label and put',
    sequenceModel: 'A1 B0 G1 A3 B0 P6 A3',
    adjustedMeasuredTimeMeasurementUnits: 140.0,
  }, {
    elementId: 100089,
    standardElementId: null,
    number: 3,
    description: 'Peel sticker off',
    sequenceModel: 'A1 B0 G1 M1 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 30.0,
  }, {
    elementId: 100089,
    standardElementId: null,
    number: 4,
    description: 'smooth sticker',
    sequenceModel: 'A0 B0 G0 M1 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 20.0,
  }, {
    elementId: 100089,
    standardElementId: null,
    number: 5,
    description: 'discard sticker back',
    sequenceModel: 'A0 B0 G0 A1 B0 P1 A0',
    adjustedMeasuredTimeMeasurementUnits: 20.0,
  }, {
    elementId: 100090,
    standardElementId: null,
    number: 1,
    description: 'Pop off side connectors',
    sequenceModel: 'A1 B0 G1 M1 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 60.0,
  }, {
    elementId: 100090,
    standardElementId: null,
    number: 2,
    description: 'Close Flaps',
    sequenceModel: 'A1 B0 G1 M3 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 200.0,
  }, {
    elementId: 100090,
    standardElementId: null,
    number: 3,
    description: 'Punch flaps into holes',
    sequenceModel: 'A0 B0 G0 M1 X0 I0 A0',
    adjustedMeasuredTimeMeasurementUnits: 40.0,
  }],
  defaultCharacteristicSetName: 'Characteristic Set DC4',
};
const propsTemplate = {
  id: 1,
  reportType: 'Method',
  clientName: 'Connors Group Client',
  filingFields: filingFieldsList,
  timeFormat: 'Seconds',
  departmentName: 'Client Department',
};
const timestamp = '2018-11-19 12:21:32 PM';

describe('Standard Method Report generation', () => {
  test('should work without filing fields', () => {
    const props = Object.assign({}, propsTemplate, {filingFields: List([])});
    const data = Object.assign({}, carharttDataTemplate, {filingFieldValues: []});
    const report = generateReport(data, props, styles, footer, header, timestamp);
    expect(report).toMatchSnapshot();
  });
});

describe('Standard Backup Report generation', () => {
  test('should work', () => {
    const props = Object.assign({}, propsTemplate, {reportType: 'Backup'});
    const data = Object.assign({}, carharttDataTemplate);
    const report = generateReport(data, props, styles, footer, header, timestamp);
    expect(report).toMatchSnapshot();
  });

  test('should work with standard element items', () => {
    const props = Object.assign({}, propsTemplate, {reportType: 'Backup'});
    const data = Object.assign({}, lbrandsDataTemplate);
    const report = generateReport(data, props, styles, footer, header, timestamp);
    expect(report).toMatchSnapshot();
  });

  test('should work with different settings', () => {
    const props = Object.assign({}, propsTemplate, {reportType: 'Backup'});
    const data = Object.assign({}, carharttDataTemplate);
    data.details.fixed = true;
    data.details.allowanceFactor = 42.0;
    const report = generateReport(data, props, styles, footer, header, timestamp);
    expect(report).toMatchSnapshot();
  });

  test('should work with blank filing fields', () => {
    const props = Object.assign({}, propsTemplate, {reportType: 'Backup'});
    props.clientName = null;

    const data = Object.assign({}, carharttDataTemplate);
    data.details.lastEditorName = null;
    data.details.applicatorName = null;
    data.details.name = null;
    data.details.laborCategoryName = null;
    data.details.classificationName = null;
    data.details.status = null;

    const report = generateReport(data, props, styles, footer, header, timestamp);
    expect(report).toMatchSnapshot();
  });
});

describe('Standard Method Time Report generation', () => {
  test('should work', () => {
    const props = Object.assign({}, propsTemplate, {reportType: 'Method Time'});
    const data = Object.assign({}, carharttDataTemplate);
    const report = generateReport(data, props, styles, footer, header, timestamp);
    expect(report).toMatchSnapshot();
  });
});

describe('Footer generation', () => {
  test('landscape', () => {
    const fn = footer(true, timestamp);
    expect(fn(1, 10)).toMatchSnapshot();
    expect(fn(3, 10)).toMatchSnapshot();
  });

  test('portrait', () => {
    const fn = footer(false, timestamp);
    expect(fn(1, 10)).toMatchSnapshot();
    expect(fn(3, 10)).toMatchSnapshot();
  });
});

describe('Header generation', () => {
  test('landscape', () => {
    const fn = header('Report title', 'client name', 12345, true);
    expect(fn(1)).toMatchSnapshot();
    expect(fn(3)).toMatchSnapshot();
  });

  test('portrait', () => {
    const fn = header('Report title', 'client name', 12345, false);
    expect(fn(1)).toMatchSnapshot();
    expect(fn(3)).toMatchSnapshot();
  });
});
