export const CLOSE_IMPORT_VOLUME_DRIVER_MAPPINGS_VALIDATION_ERRORS = 'CLOSE_IMPORT_VOLUME_DRIVER_MAPPINGS_VALIDATION_ERRORS';

export function closeImportVolumeDriverMappingsValidationErrors() {
  return {
    type: CLOSE_IMPORT_VOLUME_DRIVER_MAPPINGS_VALIDATION_ERRORS,
  };
}
