export const SHOW_IMPORT_VOLUME_DRIVER_MAPPINGS_VALIDATION_ERRORS = 'SHOW_IMPORT_VOLUME_DRIVER_MAPPINGS_VALIDATION_ERRORS';

export function showImportVolumeDriverMappingsValidationErrors() {
  return {
    type: SHOW_IMPORT_VOLUME_DRIVER_MAPPINGS_VALIDATION_ERRORS,
  };
}
