export const CLOSE_IMPORT_LOCATION_ATTRIBUTES_VALIDATION_ERRORS = 'CLOSE_IMPORT_LOCATION_ATTRIBUTES_VALIDATION_ERRORS';

export function closeImportLocationAttributesValidationErrors() {
  return {
    type: CLOSE_IMPORT_LOCATION_ATTRIBUTES_VALIDATION_ERRORS,
  };
}
