export const SHOW_IMPORT_LOCATION_ATTRIBUTES_VALIDATION_ERRORS = 'SHOW_IMPORT_LOCATION_ATTRIBUTES_VALIDATION_ERRORS';

export function showImportLocationAttributesValidationErrors() {
  return {
    type: SHOW_IMPORT_LOCATION_ATTRIBUTES_VALIDATION_ERRORS,
  };
}
