const PROCESSING = 0;
const WIM = 1;
const DRAFT_UOM = 2;
const PRODUCTION_UOM = 3;
const ATTRIBUTE = 4;
const CHARACTERISTIC = 5;
const ELEMENT = 6;
const STANDARD = 7;
const STANDARD_DETAIL = 8;
const KRONOS_LABOR_STANDARD = 9;
const KRONOS_LABOR_PERIOD = 10;
const REFLEXIS_LABOR_STANDARD = 11;
const KRONOS_LABOR_PERIOD_IMPORT_TEMPLATE = 12;
const KRONOS_LABOR_DRIVER = 14;
const KRONOS_TASK = 15;
const KRONOS_TASK_GROUP = 16;
const KRONOS_WIM = 17;
const STANDARD_BACKUP = 18;
const STANDARD_METHOD = 19;
const STANDARD_METHOD_TIME = 20;
const VOLUME_DRIVER_VALUE = 21;
const DRAFT_UOM_FOR_VDV_SETS = 22;
const PRODUCTION_UOM_FOR_VDV_SETS = 23;
const DRAFT_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS = 24;
const PRODUCTION_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS = 25;


const WIM_LABEL = 'WIM Export';
const DRAFT_UOM_LABEL = 'Draft UOM Export';
const PRODUCTION_UOM_LABEL = 'Production UOM Export';
const ATTRIBUTE_LABEL = 'Attribute Export';
const CHARACTERISTIC_LABEL = 'Characteristic Export';
const ELEMENT_LABEL = 'Element Export';
const STANDARD_LABEL = 'Standard Export';
const STANDARD_DETAIL_LABEL = 'Standard Detail Export';
const KRONOS_LABOR_STANDARD_LABEL = 'Kronos Labor Standard Export';
const KRONOS_LABOR_PERIOD_LABEL = 'Kronos Labor Period Export';
const REFLEXIS_LABOR_STANDARD_LABEL = 'Reflexis Labor Standard Export';
const KRONOS_LABOR_PERIOD_IMPORT_TEMPLATE_LABEL = 'Kronos Labor Period Import Template';
const KRONOS_LABOR_DRIVER_LABEL = 'Kronos Labor Driver Export';
const KRONOS_TASK_LABEL = 'Kronos Task Export';
const KRONOS_TASK_GROUP_LABEL = 'Kronos Task Group Export';
const KRONOS_WIM_LABEL = 'Kronos WIM Export';
const STANDARD_BACKUP_LABEL = 'Standard Backup Report';
const STANDARD_METHOD_LABEL = 'Standard Method Report';
const STANDARD_METHOD_TIME_LABEL = 'Standard Method Time Report';
const VOLUME_DRIVER_VALUE_LABEL = 'Volume Driver Value Export';
const DRAFT_UOM_FOR_VDV_SETS_LABEL = 'Draft UOM For VDV Sets Export';
const PRODUCTION_UOM_FOR_VDV_SETS_LABEL = 'Production UOM For VDV Sets Export';
const DRAFT_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS_LABEL = 'Draft Standards and Volume Drivers By Locations Export';
const PRODUCTION_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS_LABEL = 'Production Standards and Volume Drivers By Locations Export';

export function filterOptions() {
  return [
    {value: ATTRIBUTE, text: ATTRIBUTE_LABEL},
    {value: CHARACTERISTIC, text: CHARACTERISTIC_LABEL},
    {value: DRAFT_UOM, text: DRAFT_UOM_LABEL},
    {value: DRAFT_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS, text: DRAFT_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS_LABEL},
    {value: DRAFT_UOM_FOR_VDV_SETS, text: DRAFT_UOM_FOR_VDV_SETS_LABEL},
    {value: ELEMENT, text: ELEMENT_LABEL},
    {value: KRONOS_LABOR_DRIVER, text: KRONOS_LABOR_DRIVER_LABEL},
    {value: KRONOS_LABOR_PERIOD, text: KRONOS_LABOR_PERIOD_LABEL},
    {value: KRONOS_LABOR_PERIOD_IMPORT_TEMPLATE, text: KRONOS_LABOR_PERIOD_IMPORT_TEMPLATE_LABEL},
    {value: KRONOS_LABOR_STANDARD, text: KRONOS_LABOR_STANDARD_LABEL},
    {value: KRONOS_TASK, text: KRONOS_TASK_LABEL},
    {value: KRONOS_TASK_GROUP, text: KRONOS_TASK_GROUP_LABEL},
    {value: KRONOS_WIM, text: KRONOS_WIM_LABEL},
    {value: PRODUCTION_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS, text: PRODUCTION_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS_LABEL},
    {value: PRODUCTION_UOM, text: PRODUCTION_UOM_LABEL},
    {value: PRODUCTION_UOM_FOR_VDV_SETS, text: PRODUCTION_UOM_FOR_VDV_SETS_LABEL},
    {value: REFLEXIS_LABOR_STANDARD, text: REFLEXIS_LABOR_STANDARD_LABEL},
    {value: STANDARD, text: STANDARD_LABEL},
    {value: STANDARD_BACKUP, text: STANDARD_BACKUP_LABEL},
    {value: STANDARD_DETAIL, text: STANDARD_DETAIL_LABEL},
    {value: STANDARD_METHOD, text: STANDARD_METHOD_LABEL},
    {value: STANDARD_METHOD_TIME, text: STANDARD_METHOD_TIME_LABEL},
    {value: VOLUME_DRIVER_VALUE, text: VOLUME_DRIVER_VALUE_LABEL},
    {value: WIM, text: WIM_LABEL},
  ];
}

export function displayText(fileTypeCode) {
  switch (fileTypeCode) {
    case PROCESSING:
      return 'Processing...';
    case WIM:
      return WIM_LABEL;
    case DRAFT_UOM:
      return DRAFT_UOM_LABEL;
    case PRODUCTION_UOM:
      return PRODUCTION_UOM_LABEL;
    case ATTRIBUTE:
      return ATTRIBUTE_LABEL;
    case CHARACTERISTIC:
      return CHARACTERISTIC_LABEL;
    case ELEMENT:
      return ELEMENT_LABEL;
    case STANDARD:
      return STANDARD_LABEL;
    case STANDARD_DETAIL:
      return STANDARD_DETAIL_LABEL;
    case KRONOS_LABOR_STANDARD:
      return KRONOS_LABOR_STANDARD_LABEL;
    case KRONOS_LABOR_PERIOD:
      return KRONOS_LABOR_PERIOD_LABEL;
    case REFLEXIS_LABOR_STANDARD:
      return REFLEXIS_LABOR_STANDARD_LABEL;
    case KRONOS_LABOR_PERIOD_IMPORT_TEMPLATE:
      return KRONOS_LABOR_PERIOD_IMPORT_TEMPLATE_LABEL;
    case KRONOS_LABOR_DRIVER:
      return KRONOS_LABOR_DRIVER_LABEL;
    case KRONOS_TASK:
      return KRONOS_TASK_LABEL;
    case KRONOS_TASK_GROUP:
      return KRONOS_TASK_GROUP_LABEL;
    case KRONOS_WIM:
      return KRONOS_WIM_LABEL;
    case STANDARD_BACKUP:
      return STANDARD_BACKUP_LABEL;
    case STANDARD_METHOD:
      return STANDARD_METHOD_LABEL;
    case STANDARD_METHOD_TIME:
      return STANDARD_METHOD_TIME_LABEL;
    case VOLUME_DRIVER_VALUE:
      return VOLUME_DRIVER_VALUE_LABEL;
    case DRAFT_UOM_FOR_VDV_SETS:
      return DRAFT_UOM_FOR_VDV_SETS_LABEL;
    case PRODUCTION_UOM_FOR_VDV_SETS:
      return PRODUCTION_UOM_FOR_VDV_SETS_LABEL;
    case DRAFT_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS:
      return DRAFT_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS_LABEL;
    case PRODUCTION_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS:
      return PRODUCTION_STANDARDS_AND_VOLUME_DRIVERS_BY_LOCATIONS_LABEL;
  }
  throw new Error('Unknown Export Type');
}
