export const CLOSE_VOLUME_DRIVER_VALUES_IMPORT_VALIDATION_ERRORS = 'CLOSE_VOLUME_DRIVER_VALUES_IMPORT_VALIDATION_ERRORS';

export function closeVolumeDriverValuesImportValidationErrors() {
  return {
    type: CLOSE_VOLUME_DRIVER_VALUES_IMPORT_VALIDATION_ERRORS,
  };
}
