import {http} from '../../shared/services';
export const CREATE_VOLUME_DRIVER_VALUES_EXPORT_REQUEST_BACKGROUND_JOB = 'CREATE_VOLUME_DRIVER_VALUES_EXPORT_REQUEST_BACKGROUND_JOB';
export const CREATE_VOLUME_DRIVER_VALUES_EXPORT_REQUEST_BACKGROUND_JOB_PENDING = `${CREATE_VOLUME_DRIVER_VALUES_EXPORT_REQUEST_BACKGROUND_JOB}_PENDING`;
export const CREATE_VOLUME_DRIVER_VALUES_EXPORT_REQUEST_BACKGROUND_JOB_FULFILLED = `${CREATE_VOLUME_DRIVER_VALUES_EXPORT_REQUEST_BACKGROUND_JOB}_FULFILLED`;
export const CREATE_VOLUME_DRIVER_VALUES_EXPORT_REQUEST_BACKGROUND_JOB_REJECTED = `${CREATE_VOLUME_DRIVER_VALUES_EXPORT_REQUEST_BACKGROUND_JOB}_REJECTED`;

export function createVolumeDriverValuesExportRequestBackgroundJob(exportRequestId) {
  return {
    type: CREATE_VOLUME_DRIVER_VALUES_EXPORT_REQUEST_BACKGROUND_JOB,
    payload: http.get(`volume-driver-values/export/${exportRequestId}`),
  };
}
