export const SHOW_VOLUME_DRIVER_VALUES_IMPORT_VALIDATION_ERRORS = 'SHOW_IMPORT_VOLUME_DRIVER_VALUES_VALIDATION_ERRORS';

export function showVolumeDriverValuesImportValidationErrors() {
  return {
    type: SHOW_VOLUME_DRIVER_VALUES_IMPORT_VALIDATION_ERRORS,
  };
}
