export const TOGGLE_GRID_VOLUME_DRIVER_VALUES_CONFIGURATION_SIDEBAR = 'TOGGLE_GRID_VOLUME_DRIVER_VALUES_CONFIGURATION_SIDEBAR';

export function toggleVolumeDriverValuesGridConfigurationSidebar() {
  return {
    type: TOGGLE_GRID_VOLUME_DRIVER_VALUES_CONFIGURATION_SIDEBAR,
  };
}
