export const SHOW_IMPORT_VOLUME_DRIVERS_VALIDATION_ERRORS = 'SHOW_IMPORT_VOLUME_DRIVERS_VALIDATION_ERRORS';

export function showImportVolumeDriversValidationErrors() {
  return {
    type: SHOW_IMPORT_VOLUME_DRIVERS_VALIDATION_ERRORS,
  };
}
