import {http} from '../../shared/services';
export const CREATE_VDV_EXPORT_REQUEST_FOR_SELECTED_VDV_SETS_BACKGROUND_JOB = 'CREATE_VDV_EXPORT_REQUEST_FOR_SELECTED_VDV_SETS_BACKGROUND_JOB';
export const CREATE_VDV_EXPORT_REQUEST_FOR_SELECTED_VDV_SETS_BACKGROUND_JOB_PENDING = `${CREATE_VDV_EXPORT_REQUEST_FOR_SELECTED_VDV_SETS_BACKGROUND_JOB}_PENDING`;
export const CREATE_VDV_EXPORT_REQUEST_FOR_SELECTED_VDV_SETS_BACKGROUND_JOB_FULFILLED = `${CREATE_VDV_EXPORT_REQUEST_FOR_SELECTED_VDV_SETS_BACKGROUND_JOB}_FULFILLED`;
export const CREATE_VDV_EXPORT_REQUEST_FOR_SELECTED_VDV_SETS_BACKGROUND_JOB_REJECTED = `${CREATE_VDV_EXPORT_REQUEST_FOR_SELECTED_VDV_SETS_BACKGROUND_JOB}_REJECTED`;

export function createVDVExportRequestForSelectedVDVSetsBackgroundJob(exportRequestId) {
  return {
    type: CREATE_VDV_EXPORT_REQUEST_FOR_SELECTED_VDV_SETS_BACKGROUND_JOB,
    payload: http.get(`volume-driver-values/export/${exportRequestId}`),
  };
}
