export const TOGGLE_IMPORT_VOLUME_DRIVER_VALUE_SETS_VALIDATION_ERRORS = 'TOGGLE_IMPORT_VOLUME_DRIVER_VALUE_SETS_VALIDATION_ERRORS';

export function toggleImportVolumeDriverValueSetsValidationErrors() {
  return {
    type: TOGGLE_IMPORT_VOLUME_DRIVER_VALUE_SETS_VALIDATION_ERRORS,
  };
}
