export const TOGGLE_IMPORT_VOLUME_DRIVER_VALUES_VALIDATION_ERRORS = 'TOGGLE_IMPORT_VOLUME_DRIVER_VALUES_VALIDATION_ERRORS';

export function toggleImportVolumeDriverValuesValidationErrors() {
  return {
    type: TOGGLE_IMPORT_VOLUME_DRIVER_VALUES_VALIDATION_ERRORS,
  };
}
