export const CLOSE_IMPORT_ORG_HIERARCHY_LEVEL_OPTIONS_VALIDATION_ERRORS = 'CLOSE_IMPORT_ORG_HIERARCHY_LEVEL_OPTIONS_VALIDATION_ERRORS';

export function closeImportOrgHierarchyLevelOptionsValidationErrors() {
  return {
    type: CLOSE_IMPORT_ORG_HIERARCHY_LEVEL_OPTIONS_VALIDATION_ERRORS,
  };
}
