import {http} from '../../shared/services';

export const LOAD_ALL_ORG_HIERARCHY_LEVEL_OPTIONS_LIST = 'LOAD_ALL_ORG_HIERARCHY_LEVEL_OPTIONS_LIST';
export const LOAD_ALL_ORG_HIERARCHY_LEVEL_OPTIONS_LIST_PENDING = `${LOAD_ALL_ORG_HIERARCHY_LEVEL_OPTIONS_LIST}_PENDING`;
export const LOAD_ALL_ORG_HIERARCHY_LEVEL_OPTIONS_LIST_FULFILLED = `${LOAD_ALL_ORG_HIERARCHY_LEVEL_OPTIONS_LIST}_FULFILLED`;
export const LOAD_ALL_ORG_HIERARCHY_LEVEL_OPTIONS_LIST_REJECTED = `${LOAD_ALL_ORG_HIERARCHY_LEVEL_OPTIONS_LIST}_REJECTED`;

export function loadAllOrgHierarchyLevelOptionsList() {
  return {
    type: LOAD_ALL_ORG_HIERARCHY_LEVEL_OPTIONS_LIST,
    payload: http.get('org-hierarchy-levels/options/list'),
  };
}
