export const SHOW_IMPORT_ORG_HIERARCHY_LEVEL_OPTIONS_VALIDATION_ERRORS = 'SHOW_IMPORT_ORG_HIERARCHY_LEVEL_OPTIONS_VALIDATION_ERRORS';

export function showImportOrgHierarchyLevelOptionsValidationErrors() {
  return {
    type: SHOW_IMPORT_ORG_HIERARCHY_LEVEL_OPTIONS_VALIDATION_ERRORS,
  };
}
