export const CLEAR_SELECTED_DASHBOARD_LABOR_PROJECTIONS_DEPARTMENT = 'CLEAR_SELECTED_DASHBOARD_LABOR_PROJECTIONS_DEPARTMENT';

export function clearSelectedDashboardLaborProjectionsDepartment() {
  return {
    type: CLEAR_SELECTED_DASHBOARD_LABOR_PROJECTIONS_DEPARTMENT,
  };
}
