export const CLEAR_DEPARTMENT_DASHBOARD_LABOR_PROJECTIONS_FILTERS = 'CLEAR_DEPARTMENT_DASHBOARD_LABOR_PROJECTIONS_FILTERS';

export function clearDepartmentDashboardLaborProjectionsFilters() {
  return {
    type: CLEAR_DEPARTMENT_DASHBOARD_LABOR_PROJECTIONS_FILTERS,
  };
}
