export const CLEAR_DEPARTMENT_DASHBOARD_LABOR_PROJECTIONS_SORTS = 'CLEAR_DEPARTMENT_DASHBOARD_LABOR_PROJECTIONS_SORTS';

export function clearDepartmentDashboardLaborProjectionsSorts() {
  return {
    type: CLEAR_DEPARTMENT_DASHBOARD_LABOR_PROJECTIONS_SORTS,
  };
}
