import {http} from '../../shared/services';

export const GET_DASHBOARD_LABOR_PROJECTIONS_TOP_LEVEL = 'GET_DASHBOARD_LABOR_PROJECTIONS_TOP_LEVEL';
export const GET_DASHBOARD_LABOR_PROJECTIONS_TOP_LEVEL_PENDING = `${GET_DASHBOARD_LABOR_PROJECTIONS_TOP_LEVEL}_PENDING`;
export const GET_DASHBOARD_LABOR_PROJECTIONS_TOP_LEVEL_FULFILLED = `${GET_DASHBOARD_LABOR_PROJECTIONS_TOP_LEVEL}_FULFILLED`;
export const GET_DASHBOARD_LABOR_PROJECTIONS_TOP_LEVEL_REJECTED = `${GET_DASHBOARD_LABOR_PROJECTIONS_TOP_LEVEL}_REJECTED`;

export function getDashboardLaborProjectionsOrgHierarchiesTopLevel(number) {
  return {
    type: GET_DASHBOARD_LABOR_PROJECTIONS_TOP_LEVEL,
    payload: http.get(`dashboard/org-hierarchy/top-level/${number}`),
  };
}
