import {http} from '../../shared/services';

export const GET_DASHBOARD_LABOR_PROJECTIONS_SUB_LEVEL = 'GET_DASHBOARD_LABOR_PROJECTIONS_SUB_LEVEL';
export const GET_DASHBOARD_LABOR_PROJECTIONS_SUB_LEVEL_PENDING = `${GET_DASHBOARD_LABOR_PROJECTIONS_SUB_LEVEL}_PENDING`;
export const GET_DASHBOARD_LABOR_PROJECTIONS_SUB_LEVEL_FULFILLED = `${GET_DASHBOARD_LABOR_PROJECTIONS_SUB_LEVEL}_FULFILLED`;
export const GET_DASHBOARD_LABOR_PROJECTIONS_SUB_LEVEL_REJECTED = `${GET_DASHBOARD_LABOR_PROJECTIONS_SUB_LEVEL}_REJECTED`;

export function getDashboardLaborProjectionsOrgHierarchiesSubLevel(id) {
  return {
    type: GET_DASHBOARD_LABOR_PROJECTIONS_SUB_LEVEL,
    payload: http.get(`dashboard/org-hierarchy/sub-level/${id}`),
  };
}
