import {http} from '../../shared/services';

export const GET_DASHBOARD_LABOR_PROJECTIONS_LOCATIONS_BY_ORG_OPTION_ID = 'GET_DASHBOARD_LABOR_PROJECTIONS_LOCATIONS_BY_ORG_OPTION_ID';
export const GET_DASHBOARD_LABOR_PROJECTIONS_LOCATIONS_BY_ORG_OPTION_ID_PENDING = `${GET_DASHBOARD_LABOR_PROJECTIONS_LOCATIONS_BY_ORG_OPTION_ID}_PENDING`;
export const GET_DASHBOARD_LABOR_PROJECTIONS_LOCATIONS_BY_ORG_OPTION_ID_FULFILLED = `${GET_DASHBOARD_LABOR_PROJECTIONS_LOCATIONS_BY_ORG_OPTION_ID}_FULFILLED`;
export const GET_DASHBOARD_LABOR_PROJECTIONS_LOCATIONS_BY_ORG_OPTION_ID_REJECTED = `${GET_DASHBOARD_LABOR_PROJECTIONS_LOCATIONS_BY_ORG_OPTION_ID}_REJECTED`;

export function getDashboardLaborProjectionsLocationsByOrgOptionId(id) {
  return {
    type: GET_DASHBOARD_LABOR_PROJECTIONS_LOCATIONS_BY_ORG_OPTION_ID,
    payload: http.get(`dashboard/locations/${id}`),
  };
}
