import {http} from '../../../shared/services';

export const LOAD_INTEGRATION_ENDPOINT_REQUESTS = 'REFLEXIS/INTEGRATION_ENDPOINT/LOAD_INTEGRATION_ENDPOINT_REQUESTS';
export const LOAD_INTEGRATION_ENDPOINT_REQUESTS_PENDING = `${LOAD_INTEGRATION_ENDPOINT_REQUESTS}_PENDING`;
export const LOAD_INTEGRATION_ENDPOINT_REQUESTS_FULFILLED = `${LOAD_INTEGRATION_ENDPOINT_REQUESTS}_FULFILLED`;
export const LOAD_INTEGRATION_ENDPOINT_REQUESTS_REJECTED = `${LOAD_INTEGRATION_ENDPOINT_REQUESTS}_REJECTED`;

export function loadIntegrationEndpointRequests(id) {
  return {
    type: LOAD_INTEGRATION_ENDPOINT_REQUESTS,
    payload: http.get(`reflexis/endpoints/${id}/requests`),
  };
}
