export const SHOULD_RELOAD_VOLUME_DRIVER_MAPPING_VARIABLES_PAGE = 'SHOULD_RELOAD_VOLUME_DRIVER_MAPPING_VARIABLES_PAGE';

export function shouldReloadVolumeDriverMappingVariablesPage() {
  return {
    type: SHOULD_RELOAD_VOLUME_DRIVER_MAPPING_VARIABLES_PAGE,
  };
}
