export const CLEAR_CHARACTERISTICS_LIST_SORTS = 'CLEAR_CHARACTERISTICS_LIST_SORTS';
export const CLEAR_CHARACTERISTICS_LIST_SORTS_PENDING = `${CLEAR_CHARACTERISTICS_LIST_SORTS}_PENDING`;
export const CLEAR_CHARACTERISTICS_LIST_SORTS_FULFILLED = `${CLEAR_CHARACTERISTICS_LIST_SORTS}_FULFILLED`;
export const CLEAR_CHARACTERISTICS_LIST_SORTS_REJECTED = `${CLEAR_CHARACTERISTICS_LIST_SORTS}_REJECTED`;

export function clearCharacteristicsListSorts() {
  return {
    type: CLEAR_CHARACTERISTICS_LIST_SORTS,
    payload: Promise.resolve(),
  };
}
