export const CLOSE_IMPORT_CHARACTERISTICS_VALIDATION_ERRORS = 'CLOSE_IMPORT_CHARACTERISTICS_VALIDATION_ERRORS';

export function closeImportCharacteristicsValidationErrors() {
  return {
    type: CLOSE_IMPORT_CHARACTERISTICS_VALIDATION_ERRORS,
  };
}
