
export const FILTER_CHARACTERISTICS_LIST = 'FILTER_CHARACTERISTICS_LIST';
export const FILTER_CHARACTERISTICS_LIST_PENDING = `${FILTER_CHARACTERISTICS_LIST}_PENDING`;
export const FILTER_CHARACTERISTICS_LIST_FULFILLED = `${FILTER_CHARACTERISTICS_LIST}_FULFILLED`;
export const FILTER_CHARACTERISTICS_LIST_REJECTED = `${FILTER_CHARACTERISTICS_LIST}_REJECTED`;

export function filterCharacteristicsList(filter) {
  return {
    type: FILTER_CHARACTERISTICS_LIST,
    payload: Promise.resolve(filter),
  };
}
