export const SHOW_IMPORT_CHARACTERISTICS_VALIDATION_ERRORS = 'SHOW_IMPORT_CHARACTERISTICS_VALIDATION_ERRORS';

export function showImportCharacteristicsValidationErrors() {
  return {
    type: SHOW_IMPORT_CHARACTERISTICS_VALIDATION_ERRORS,
  };
}
