export const SORT_CHARACTERISTICS_LIST = 'SORT_CHARACTERISTICS_LIST';
export const SORT_CHARACTERISTICS_LIST_PENDING = `${SORT_CHARACTERISTICS_LIST}_PENDING`;
export const SORT_CHARACTERISTICS_LIST_FULFILLED = `${SORT_CHARACTERISTICS_LIST}_FULFILLED`;
export const SORT_CHARACTERISTICS_LIST_REJECTED = `${SORT_CHARACTERISTICS_LIST}_REJECTED`;

export function sortCharacteristicsList(sort) {
  return {
    type: SORT_CHARACTERISTICS_LIST,
    payload: Promise.resolve(sort),
  };
}
