export const TOGGLE_CHARACTERISTICS_LIST_BULK_EDIT_SIDEBAR = 'TOGGLE_CHARACTERISTIC_LIST_BULK_EDIT_SIDEBAR';

export function toggleCharacteristicsListBulkEditSidebar() {
  return {
    type: TOGGLE_CHARACTERISTICS_LIST_BULK_EDIT_SIDEBAR,
  };
}
