export const TOGGLE_CHARACTERISTIC_CONFIGURE_COLUMN_VISIBILITY = 'TOGGLE_CHARACTERISTIC_CONFIGURE_COLUMN_VISIBILITY';
export const TOGGLE_CHARACTERISTIC_CONFIGURE_COLUMN_VISIBILITY_PENDING = `${TOGGLE_CHARACTERISTIC_CONFIGURE_COLUMN_VISIBILITY}_PENDING`;
export const TOGGLE_CHARACTERISTIC_CONFIGURE_COLUMN_VISIBILITY_FULFILLED = `${TOGGLE_CHARACTERISTIC_CONFIGURE_COLUMN_VISIBILITY}_FULFILLED`;
export const TOGGLE_CHARACTERISTIC_CONFIGURE_COLUMN_VISIBILITY_REJECTED = `${TOGGLE_CHARACTERISTIC_CONFIGURE_COLUMN_VISIBILITY}_REJECTED`;

export function toggleCharacteristicConfigureColumnVisibility(field, visibility) {
  return {
    type: TOGGLE_CHARACTERISTIC_CONFIGURE_COLUMN_VISIBILITY,
    payload: Promise.resolve({field, visibility}),
  };
}

export default toggleCharacteristicConfigureColumnVisibility;

