export const CLOSE_IMPORT_HIERARCHY_LEVELS_VALIDATION_ERRORS_MODAL = 'CLOSE_IMPORT_HIERARCHY_LEVELS_VALIDATION_ERRORS_MODAL';

export function closeImportHierarchyLevelsValidationErrorsModal() {
  return {
    type: CLOSE_IMPORT_HIERARCHY_LEVELS_VALIDATION_ERRORS_MODAL,
  };
}
